<?php


/**
 * This class adds structure of 'question' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jul  2 14:16:05 2012
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class QuestionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.QuestionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(QuestionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(QuestionPeer::TABLE_NAME);
		$tMap->setPhpName('Question');
		$tMap->setClassname('Question');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('SURVEY_ID', 'SurveyId', 'INTEGER', 'survey', 'ID', false, null);

		$tMap->addColumn('HEADING', 'Heading', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CONTENT', 'Content', 'LONGVARCHAR', false, null);

		$tMap->addColumn('NEXT_ID', 'NextId', 'INTEGER', false, null);

		$tMap->addColumn('IS_RANGE', 'IsRange', 'VARCHAR', false, 3);

		$tMap->addColumn('SOURCE_TEXT', 'SourceText', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('EXTRA1', 'Extra1', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA2', 'Extra2', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA3', 'Extra3', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA4', 'Extra4', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA5', 'Extra5', 'LONGVARCHAR', false, null);

	} // doBuild()

} // QuestionMapBuilder
