<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/13 14:15:02
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'problem' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'loginprocess' => 
  array (
    'is_secure' => false,
  ),
  'requestnewpassword' => 
  array (
    'is_secure' => false,
  ),
  'requestnewpasswordprocess' => 
  array (
    'is_secure' => false,
  ),
  'newpassword' => 
  array (
    'is_secure' => false,
  ),
  'newpasswordprocess' => 
  array (
    'is_secure' => false,
  ),
);
