<?php use_helper('Object'); ?>
<!-- This file contains the CA Step 1 form           -->

  <div class="dabblePageContainer dabblePageNoNavigation">
    <div class="dabblePageLeftShadow">
      <div class="dabblePageRightShadow">
        <div class=
        "dabblePage dabblePageWithLogo dabbleSearchPage">
          <div class="dabblePageHeader" id="dabblePageTop">
            <div class="dabblePageLogo">
              <!--[if lte IE 6]><span style="display:block;width:176px;height:57px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/launchpad/images/logo250857176.png',sizingMethod='crop')"><![endif]--><img alt=""
              height="57" width="176" class="png24bit" src=
              "/launchpad/images/logo250857176.png" /> <!-- /publish/logo250857176.png -->
              <!--[if lte IE 6]></span><![endif]-->
            </div>

    <h1>&nbsp;</h1>

            <div id="dabblePageMenuLink" class=
            "dabblePageMobileOnly dabblePageNavigationLinks">
               
            </div>
          </div>

          <div id="dabblePageContent">

<?php echo form_tag('ctiforms/coachTrainingProcess', 'method=post id=dabblePageForm  class=dabblePageForm name=dabblePageForm  enctype=multipart/form-data') ?>

                <input type="hidden" name="referer" value="<?php echo url_for("ctiforms/coachTrainingThankYou") ?>" />




<div class="dabblePageSection dabblePageSectionFull">
<div class="dabblePageColumn dabblePageColumn1">

<!--
<div class="dabblePageTextItem">
<div class="dabblePageText">
<p></p>
</div>
</div>
-->


<div class="dabblePageTextItem">
<div class="dabblePageText">
    <p>&nbsp;</p>
    <p>&nbsp;</p>

<h1>CTI Coach Training Program Scholarship Application</h1>



<p>You will need to complete this form in one sitting. Please be sure that you have at least 30 minutes available before you begin. The pre-requisite to applying for this scholarship is completion of the Co-active Coaching Fundamentals course.</p>

</div>
</div>


    <h1>Section A: You</h1>
<!-- ================= Generated by /Users/thomas/00-CTI/73-Scholarship-Forms/./iterate-fields.pl ================= -->

<!-- ================= TEXT INPUT: last_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="last_name">First Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="last_name" type="text" class="text" name="coachtraining[first_name]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: first_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="first_name">Last Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="first_name" type="text" class="text" name="coachtraining[last_name]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: email1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="email1">Email Address</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="email1" type="text" class="text" name="coachtraining[email1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<h2>Permanent Address</h2>
<!-- ================= TEXT INPUT: perm_address1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address1">Address1</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_address1" type="text" class="text" name="coachtraining[perm_address1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_address2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address2">Address2</label>
   </div>
   <div class="dabblePageFormField">
      <input id="perm_address2" type="text" class="text" name="coachtraining[perm_address2]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_city ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_city">City</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_city" type="text" class="text" name="coachtraining[perm_city]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_state ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_state">State</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_state" type="text" class="text" name="coachtraining[perm_state_prov]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_zip_postcode ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_zip_postcode">Zip Code</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_zip_postcode" type="text" class="text" name="coachtraining[perm_zip_postcode]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_country">Country</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_country" type="text" class="text" name="coachtraining[perm_country]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>


<h2>Other Address</h2>

<!-- ================= TEXT INPUT: other_address1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_address1">Address1</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_address1" type="text" class="text" name="coachtraining[other_address1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_address2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_address2">Address2</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_address2" type="text" class="text" name="coachtraining[other_address2]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_city ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_city">City</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_city" type="text" class="text" name="coachtraining[other_city]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_state ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_state">State</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_state" type="text" class="text" name="coachtraining[other_state_prov]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_zip_postcode ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_zip_postcode">Zip Code</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_zip_postcode" type="text" class="text" name="coachtraining[other_zip_postcode]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_country">Country</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_country" type="text" class="text" name="coachtraining[other_country]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone1">Phone</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="telephone1" type="text" class="text" name="coachtraining[telephone1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone2">Mobile</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="telephone2" type="text" class="text" name="coachtraining[telephone2]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: referred_by ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="referred_by">I was referred to the scholarship program by</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="referred_by" type="text" class="text" name="coachtraining[referred_by]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>







<h1>Section B: Program Preference</h1>



<!-- ================= TEXT INPUT: program_preference ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="program_preference">Please choose one:</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="program_preference1" type="radio" name="coachtraining[program_preference]" value="full program" checked /> I am applying for a scholarship to the full Coach Training Program which will include Core Curriculum courses and the Certification Program.<br /><br />
      <input id="program_preference2" type="radio" name="coachtraining[program_preference]" value="full program" /> I am applying for a scholarship to the Certification Program only.
   </div>
</div>
<div style="clear:both">&nbsp;</div>



<!-- ================= TEXT INPUT: core_preferred_date1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="core_preferred_date1">Core Curriculum course location and date, 1st Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="core_preferred_date1" type="text" class="text" name="coachtraining[core_preferred_date1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: core_preferred_date2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="core_preferred_date2">Core Curriculum course location and date, 2nd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="core_preferred_date2" type="text" class="text" name="coachtraining[core_preferred_date2]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: core_preferred_date3 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="core_preferred_date3">Core Curriculum course location and date, 3rd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="core_preferred_date3" type="text" class="text" name="coachtraining[core_preferred_date3]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: cert_preferred_date1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="cert_preferred_date1">Certification Program start month, 1st Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="cert_preferred_date1" type="text" class="text" name="coachtraining[cert_preferred_date1]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: cert_preferred_date2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="cert_preferred_date2">Certification Program start month, 2nd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="cert_preferred_date2" type="text" class="text" name="coachtraining[cert_preferred_date2]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: cert_preferred_date3 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="cert_preferred_date3">Certification Program start month, 3rd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="cert_preferred_date3" type="text" class="text" name="coachtraining[cert_preferred_date3]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_choose ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_choose">What had you choose CTI's Coach Training Program?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="what_choose" cols="40" rows="4" name="coachtraining[what_choose]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: fundamentals_exp ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="fundamentals_exp">Tell us about your Co-Active Coaching Fundamentals course experience.</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="fundamentals_exp" cols="40" rows="4" name="coachtraining[fundamentals_exp]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: your_vision ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="your_vision">What's your vision for becoming a Co-Active Coach? What's the impact you want to have in the world?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="your_vision" cols="40" rows="4" name="coachtraining[your_vision]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: how_support ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="how_support">How will CTI training support you in creating your vision?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="how_support" cols="40" rows="4" name="coachtraining[how_support]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: why_applying ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="why_applying">Why are you applying for the scholarship?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="why_applying" cols="40" rows="4" name="coachtraining[why_applying]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_size ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_size">We want you to have some investment in the program. What size scholarship do you need to make this program possible for you or what percentage discount do you need?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="what_size" cols="40" rows="4" name="coachtraining[what_size]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: or attach a resume with your application./background ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="or attach a resume with your application./background">Please tell us about your background and/or attach a resume with your application.</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="background" cols="40" rows="4" name="coachtraining[background]"></textarea><br /><br />
<input type="file" id="bio_resume" name="bio_filename" />
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: anything_else  ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="anything_else ">Is there anything else you want us to know about you?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="anything_else " cols="40" rows="4" name="coachtraining[anything_else]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>










<h1>Section:&nbsp; D:&nbsp; Agreements</h1>

<p>If I receive and accept the scholarship:</p>

<ul>
<li>I understand I may not get the program date(s) I prefer.</li>
<li>I understand that CTI will determine the amount of the scholarship I will receive.</li>
<li>I will complete the program with full participation and commitment.</li>
<li>CTI may publish information about me and my impact in the world in marketing and PR materials.</li>
</ul>


<!-- ================= TEXT INPUT: understood_agreement ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="understood_agreement">I have read and understood the Agreements (please insert your initials).</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="understood_agreement" type="text" class="text" name="coachtraining[understood_agreements]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>







<p class="qwed"></p>
             
                  <div class="dabblePageTextItem">
                    <div class="dabblePageText">
                      <p>
                      </em></p>

                    </div>
                  </div>
                </div>
              </div>

              <div class="clear"></div>

              <div class=
              "dabblePageSection dabblePageSectionFormActions">
                <div class="dabblePageColumn dabblePagColmn1">
                  <div class="dabblePageFormActions">
                    <span class=
                    "dabblePageFormButton dabblePageFormSubmit">
					<input name="save"
                    accesskey="s" id="dabblePageFormSubmit" value=
                    "Submit Form" type="submit" class=
                    "submit" /> 
					<?php echo button_to('Cancel',$referer, 'class=submit') ?>	
					<!-- <input name="cancel" value="Cancel"
                    type="submit" class="submit" /> -->
					</span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="dabblePageBottomLeftShadow"></div>

    <div class="dabblePageBottomRightShadow"></div>

    <div class="dabblePageBottomShadow"></div>
  </div>