<?php use_helper('Object'); ?>
<!-- This file contains the CA Step 1 form           -->

  <div class="dabblePageContainer dabblePageNoNavigation">
    <div class="dabblePageLeftShadow">
      <div class="dabblePageRightShadow">
        <div class=
        "dabblePage dabblePageWithLogo dabbleSearchPage">
          <div class="dabblePageHeader" id="dabblePageTop">
            <div class="dabblePageLogo">
              <!--[if lte IE 6]><span style="display:block;width:176px;height:57px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/launchpad/images/logo250857176.png',sizingMethod='crop')"><![endif]--><img alt=""
              height="57" width="176" class="png24bit" src=
              "/launchpad/images/logo250857176.png" /> <!-- /publish/logo250857176.png -->
              <!--[if lte IE 6]></span><![endif]-->
            </div>

    <h1>&nbsp;</h1>

            <div id="dabblePageMenuLink" class=
            "dabblePageMobileOnly dabblePageNavigationLinks">
               
            </div>
          </div>

          <div id="dabblePageContent">

<?php echo form_tag('ctiforms/leadershipProcess', 'method=post id=dabblePageForm  class=dabblePageForm name=dabblePageForm  enctype=multipart/form-data') ?>

                <input type="hidden" name="referer" value="<?php echo url_for("ctiforms/leadershipThankYou") ?>" />




<div class="dabblePageSection dabblePageSectionFull">
<div class="dabblePageColumn dabblePageColumn1">

<!--
<div class="dabblePageTextItem">
<div class="dabblePageText">
<p></p>
</div>
</div>
-->


<div class="dabblePageTextItem">
<div class="dabblePageText">
    <p>&nbsp;</p>
    <p>&nbsp;</p>

<h1>CTI Leadership Program Scholarship Application</h1>



<p>You will need to complete this form in one sitting. Please be sure that you have at least 30 minutes available before you begin.</p>

</div>
</div>


    <h1>Section A: You</h1>
<!-- ================= Generated by /Users/thomas/00-CTI/73-Scholarship-Forms/./iterate-fields.pl ================= -->

<!-- ================= TEXT INPUT: last_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="last_name">First Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="last_name" type="text" class="text" name="leadership[first_name]" value="<?php if(isset($profile)){echo $profile->getFirstName();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: first_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="first_name">Last Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="first_name" type="text" class="text" name="leadership[last_name]" value="<?php if(isset($profile)){echo $profile->getLastName();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: email1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="email1">Email Address</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="email1" type="text" class="text" name="leadership[email1]" value="<?php if(isset($profile)){echo $profile->getEmail1();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<h2>Permanent Address</h2>
<!-- ================= TEXT INPUT: perm_address1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address1">Address1</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_address1" type="text" class="text" name="leadership[perm_address1]" value="<?php if(isset($profile)){echo $profile->getPermAddress1();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_address2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address2">Address2</label>
   </div>
   <div class="dabblePageFormField">
      <input id="perm_address2" type="text" class="text" name="leadership[perm_address2]" value="<?php if(isset($profile)){echo $profile->getPermAddress2();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_city ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_city">City</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_city" type="text" class="text" name="leadership[perm_city]" value="<?php if(isset($profile)){echo $profile->getPermCity();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_state ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_state">State</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_state" type="text" class="text" name="leadership[perm_state_prov]" value="<?php if(isset($profile)){echo $profile->getPermStateProv();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_zip_postcode ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_zip_postcode">Zip Code</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_zip_postcode" type="text" class="text" name="leadership[perm_zip_postcode]" value="<?php if(isset($profile)){echo $profile->getPermZipPostcode();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_country">Country</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="perm_country" type="text" class="text" name="leadership[perm_country]" value="<?php if(isset($profile)){echo $profile->getPermCountry();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>


<h2>Other Address</h2>

<!-- ================= TEXT INPUT: other_address1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_address1">Address1</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_address1" type="text" class="text" name="leadership[other_address1]" value="<?php if(isset($profile)){echo $profile->getOtherAddress1();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_address2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_address2">Address2</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_address2" type="text" class="text" name="leadership[other_address2]" value="<?php if(isset($profile)){echo $profile->getOtherAddress2();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_city ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_city">City</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_city" type="text" class="text" name="leadership[other_city]" value="<?php if(isset($profile)){echo $profile->getOtherCity();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_state ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_state">State</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_state" type="text" class="text" name="leadership[other_state_prov]" value="<?php if(isset($profile)){echo $profile->getOtherStateProv();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_zip_postcode ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_zip_postcode">Zip Code</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_zip_postcode" type="text" class="text" name="leadership[other_zip_postcode]" value="<?php if(isset($profile)){echo $profile->getOtherZipPostcode();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: other_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="other_country">Country</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="other_country" type="text" class="text" name="leadership[other_country]" value="<?php if(isset($profile)){echo $profile->getOtherCountry();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone1">Phone</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="telephone1" type="text" class="text" name="leadership[telephone1]" value="<?php if(isset($profile)){echo $profile->getTelephone1();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone2">Mobile</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="telephone2" type="text" class="text" name="leadership[telephone2]" value="<?php if(isset($profile)){echo $profile->getTelephone2();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: referred_by ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="referred_by">I was referred to the scholarship program by</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="referred_by" type="text" class="text" name="leadership[referred_by]" value="<?php if(isset($profile)){echo $profile->getReferredBy();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>



<h1>Section B: Program Preference</h1>

<!-- ================= SELECT: program_preference ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="program_preference1">Please choose one:</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
<?php 
$pref = 'full R1-R4';
if(isset($lead)){
 $pref = $lead->getProgramPreference();
} 
?>
<input type="radio" id="program_preference1" name="leadership[program_preference]" <?php if(preg_match('/full/',$pref)){echo 'checked';} ?> value="full R1-R4" /> I am applying for a scholarship to a full leadership program, R1-R4.<br /><br />
<input type="radio" id="program_preference2" name="leadership[program_preference]" <?php if(preg_match('/part/',$pref)){echo 'checked';} ?> value="partial R2-R4" /> I have completed the R1 Stand Alone, Creating From Self, and am applying for a scholarship to the R2-R4 of a leadership tribe.
      
   </div>
</div>
<div style="clear:both">&nbsp;</div>



<!-- ================= TEXT INPUT: preferred_date1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="preferred_date1">Preferred Program Date, 1st Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="preferred_date1" type="text" class="text" name="leadership[preferred_date1]" value="<?php if(isset($lead)){echo $lead->getPreferredDate1();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: preferred_date2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="preferred_date2">Preferred Program Date, 2nd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="preferred_date2" type="text" class="text" name="leadership[preferred_date2]" value="<?php if(isset($lead)){echo $lead->getPreferredDate2();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: preferred_date3 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="preferred_date3">Preferred Program Date, 3rd Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="preferred_date3" type="text" class="text" name="leadership[preferred_date3]" value="<?php if(isset($lead)){echo $lead->getPreferredDate3();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>


<h1>Section C: Questions</h1>
<!-- ================= TEXTAREA: how_started ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="how_started">How did you get started with CTI?  What inspired you to take CTI programs?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="how_started" cols="40" rows="4" name="leadership[how_started]"><?php if(isset($lead)){echo $lead->getHowStarted();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_impact ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_impact">What impact has your training with CTI had on you?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="what_impact" cols="40" rows="4" name="leadership[what_impact]"><?php if(isset($lead)){echo $lead->getWhatImpact();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: why_take ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="why_take">Why do you want to take the leadership program?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="why_take" cols="40" rows="4" name="leadership[why_take]"><?php if(isset($lead)){echo $lead->getWhyTake();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: desired_impact ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="desired_impact">What's your desired impact in the world? What would you do in the world with the training you received?</label><!-- ' -->
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="desired_impact" cols="40" rows="4" name="leadership[desired_impact]"><?php if(isset($lead)){echo $lead->getDesiredImpact();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: how_accountable ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="how_accountable">How will you be accountable for your impact in the world after you complete the program?  How will you report that back to CTI?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="how_accountable" cols="40" rows="4" name="leadership[how_accountable]"><?php if(isset($lead)){echo $lead->getHowAccountable();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_bring ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_bring">What will you bring to the program?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="what_bring" cols="40" rows="4" name="leadership[what_bring]"><?php if(isset($lead)){echo $lead->getWhatBring();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: why_applying ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="why_applying">Why are you applying for the scholarship?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="why_applying" cols="40" rows="4" name="leadership[why_applying]"><?php if(isset($lead)){echo $lead->getWhyApplying();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_size ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_size">We want you to have some investment in the program. What size scholarship do you need to make this program possible for you or what percentage discount do you need?</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="what_size" cols="40" rows="4" name="leadership[what_size]"><?php if(isset($lead)){echo $lead->getWhatSize();} ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: background ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="background">Please tell us about your background and-or attach a resume with your application.</label>
       </div>
       <div class="dabblePageFormField dabblePageFormItemRequired">
           <textarea id="background" cols="40" rows="4" name="leadership[background]"><?php if(isset($lead)){echo $lead->getBackground();} ?></textarea><br /><br />
<input type="file" id="bio_resume" name="bio_filename" />
       </div>
   </div>
<div style="clear:both">&nbsp;</div>


<h1>Section:&nbsp; D:&nbsp; Agreements</h1>

<p>If I receive and accept the scholarship:</p>

<ul>
<li>I understand I may not get the program date(s) I prefer.</li>
<li>I understand that CTI will determine the amount of the scholarship I will receive.</li>
<li>I will complete the leadership program with full participation and commitment.</li>
<li>After the program I will follow up with CTI to let them know about my impact in the world as outlined in my accountability agreement.</li>
<li>CTI may publish information about my leadership project in marketing and PR materials.</li>
</ul>


<!-- ================= TEXT INPUT: understood_agreement ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="understood_agreement">I have read and understood the Agreements (please insert your initials).</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input id="understood_agreement" type="text" class="text" name="leadership[understood_agreement]" value="<?php if(isset($lead)){echo $lead->getUnderstoodAgreements();} ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>







<p class="qwed"></p>
             
                  <div class="dabblePageTextItem">
                    <div class="dabblePageText">
                      <p>
                      </em></p>

                    </div>
                  </div>
                </div>
              </div>

              <div class="clear"></div>

              <div class=
              "dabblePageSection dabblePageSectionFormActions">
                <div class="dabblePageColumn dabblePagColmn1">
                  <div class="dabblePageFormActions">
                    <span class=
                    "dabblePageFormButton dabblePageFormSubmit">
					<input name="save"
                    accesskey="s" id="dabblePageFormSubmit" value=
                    "Submit Form" type="submit" class=
                    "submit" /> 
					<?php echo button_to('Cancel',$referer, 'class=submit') ?>	
					<!-- <input name="cancel" value="Cancel"
                    type="submit" class="submit" /> -->
					</span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="dabblePageBottomLeftShadow"></div>

    <div class="dabblePageBottomRightShadow"></div>

    <div class="dabblePageBottomShadow"></div>
  </div>