<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/08/28 23:40:03
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
);
