<?php use_helper('Object'); ?>
<!-- This file contains the CA Step 1 form           -->

  <div class="dabblePageContainer dabblePageNoNavigation">
    <div class="dabblePageLeftShadow">
      <div class="dabblePageRightShadow">
        <div class=
        "dabblePage dabblePageWithLogo dabbleSearchPage">
          <div class="dabblePageHeader" id="dabblePageTop">
            <div class="dabblePageLogo">
              <!--[if lte IE 6]><span style="display:block;width:176px;height:57px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/launchpad/images/logo250857176.png',sizingMethod='crop')"><![endif]--><img alt=""
              height="57" width="176" class="png24bit" src=
              "/launchpad/images/logo250857176.png" /> <!-- /publish/logo250857176.png -->
              <!--[if lte IE 6]></span><![endif]-->
            </div>

    <h1>&nbsp;</h1>

            <div id="dabblePageMenuLink" class=
            "dabblePageMobileOnly dabblePageNavigationLinks">
               
            </div>
          </div>

          <div id="dabblePageContent">

<?php echo form_tag('ctiforms/AnnualQuestionnaireProcess', 'method=post id=dabblePageForm  class=dabblePageForm name=dabblePageForm') ?>

                <input type="hidden" name="referer" value="<?php echo url_for("ctiforms/AnnualQuestionnaireThankYou") ?>" />




<div class="dabblePageSection dabblePageSectionFull">
<div class="dabblePageColumn dabblePageColumn1">

<!--
<div class="dabblePageTextItem">
<div class="dabblePageText">
<p></p>
</div>
</div>
-->


<div class="dabblePageTextItem">
<div class="dabblePageText">
    <p>&nbsp;</p>
    <p>&nbsp;</p>

<h1>Co-Active Leadership Program 2015</h1>

<p><strong>The Coaches Training Institute</strong></p>

<p>Use the drop down menu below to enter your 1st and 2nd choice of leadership program to assist. Please check your personal calendar first for any potential scheduling conflicts. You must be available for all 4 weeks (listed in the accompanying letter) and be able to arrive the day before to set up and stay 2+ hours after the retreat ends to complete logistics. Please include your I AM Type, graduating tribe and leaders, and contact info to help us with the selection process.</p>
<p>Reply promptly. Please note: filling out this questionnaire does not guarantee you an assistant spot. We hope to have all selections made by early next year.</p>

</div>
</div>


<!-- ================= Generated by /Users/thomas/00-CTI/90-Leadership-Annual/iterate-fields.pl ================= -->

<!-- ================= TEXT INPUT: first_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="first_name">First Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[first_name]" id=first_name value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: last_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="last_name">Last Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[last_name]" id=last_name value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: contact_telephone ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="contact_telephone">Contact Telephone</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[contact_telephone]" id=contact_telephone value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: contact_email ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="contact_email">Contact Email</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[contact_email]" id=contact_email value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>


<!-- ================= SELECT: tribe_first_choice ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="tribe_first_choice">Tribe 1<sup>st</sup> Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <select id="tribe_first_choice" name="annual[tribe_first_choice]">
      <?php  echo options_for_select( $tribes ) ?>
      </select>
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= SELECT: tribe_second_choice ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="tribe_second_choice">Tribe 2<sup>nd</sup> Choice</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <select id="tribe_second_choice" name="annual[tribe_second_choice]">
      <?php  echo options_for_select( $tribes ) ?>
      </select>
   </div>
</div>
<div style="clear:both">&nbsp;</div>


<!-- ================= SELECT: i_am_type_ ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="i_am_type_">I AM Type</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <select id="i_am_type_" name="annual[i_am_type]">
      <?php  echo options_for_select( $iam_types ) ?>
      </select>
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: your_tribe_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="your_tribe_name">Your Tribe Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[your_tribe_name]" id=your_tribe_name value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: your_tribe_leader_1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="your_tribe_leader_1">Tribe Leader 1</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[your_tribe_leader_1]" id=your_tribe_leader_1 value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: your_tribe_leader_2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="your_tribe_leader_2">Tribe Leader 2</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="annual[your_tribe_leader_2]" id=your_tribe_leader_2 value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: anything_else_youd_like_us_to_know ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="anything_else_youd_like_us_to_know">Anything else you'd like us to know?</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="anything_else_youd_like_us_to_know" cols="40" rows="4" name="annual[anything_else_youd_like_us_to_know]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>













<!-- TEXT EXAMPLE -->
<!--
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="name">*First and Last Name</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <input type="text" class="text" name="cert[name]" value="" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>
-->


<!-- SELECT EXAMPLE -->
<!--
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="month-to-begin-certification">*What month would you like to begin certification?</label>
   </div>
   <div class="dabblePageFormField dabblePageFormItemRequired">
      <select  name="cert[month-to-begin-certification]">
      <?php  echo options_for_select( $months ) ?>
      </select>
   </div>
</div>
<div style="clear:both">&nbsp;</div>
-->


<!-- TEXTAREA EXAMPLE -->
<!--
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="w1312">Comments</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="w1312" cols="40" rows="4" name="cert[comments]"></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>
-->



<p class="qwed"></p>
             
                  <div class="dabblePageTextItem">
                    <div class="dabblePageText">
                      <p>
                      </em></p>

                    </div>
                  </div>
                </div>
              </div>

              <div class="clear"></div>

              <div class=
              "dabblePageSection dabblePageSectionFormActions">
                <div class="dabblePageColumn dabblePagColmn1">
                  <div class="dabblePageFormActions">
                    <span class=
                    "dabblePageFormButton dabblePageFormSubmit">
					<input name="save"
                    accesskey="s" id="dabblePageFormSubmit" value=
                    "Submit Form" type="submit" class=
                    "submit" /> 
					<?php echo button_to('Cancel',$referer, 'class=submit') ?>	
					<!-- <input name="cancel" value="Cancel"
                    type="submit" class="submit" /> -->
					</span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="dabblePageBottomLeftShadow"></div>

    <div class="dabblePageBottomRightShadow"></div>

    <div class="dabblePageBottomShadow"></div>
  </div>