<?php

/**
 * Base class that represents a row from the 'registrant' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Mar 18 23:28:37 2011
 *
 * @package    lib.model.om
 */
abstract class BaseRegistrant extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RegistrantPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the first_name field.
	 * @var        string
	 */
	protected $first_name;

	/**
	 * The value for the middle_name field.
	 * @var        string
	 */
	protected $middle_name;

	/**
	 * The value for the last_name field.
	 * @var        string
	 */
	protected $last_name;

	/**
	 * The value for the address_line1 field.
	 * @var        string
	 */
	protected $address_line1;

	/**
	 * The value for the address_line2 field.
	 * @var        string
	 */
	protected $address_line2;

	/**
	 * The value for the city field.
	 * @var        string
	 */
	protected $city;

	/**
	 * The value for the state field.
	 * @var        string
	 */
	protected $state;

	/**
	 * The value for the zip field.
	 * @var        string
	 */
	protected $zip;

	/**
	 * The value for the country field.
	 * @var        string
	 */
	protected $country;

	/**
	 * The value for the phone field.
	 * @var        string
	 */
	protected $phone;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the workshop_id field.
	 * @var        int
	 */
	protected $workshop_id;

	/**
	 * The value for the conf_email_sent_to_client_at field.
	 * @var        string
	 */
	protected $conf_email_sent_to_client_at;

	/**
	 * The value for the cookie_name field.
	 * @var        string
	 */
	protected $cookie_name;

	/**
	 * The value for the cookie_value field.
	 * @var        string
	 */
	protected $cookie_value;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Workshop
	 */
	protected $aWorkshop;

	/**
	 * @var        array RegistrantExtra[] Collection to store aggregation of RegistrantExtra objects.
	 */
	protected $collRegistrantExtras;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRegistrantExtras.
	 */
	private $lastRegistrantExtraCriteria = null;

	/**
	 * @var        array WorkshopRegistrant[] Collection to store aggregation of WorkshopRegistrant objects.
	 */
	protected $collWorkshopRegistrants;

	/**
	 * @var        Criteria The criteria used to select the current contents of collWorkshopRegistrants.
	 */
	private $lastWorkshopRegistrantCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'RegistrantPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFirstName()
	{
		return $this->first_name;
	}

	/**
	 * Get the [middle_name] column value.
	 * 
	 * @return     string
	 */
	public function getMiddleName()
	{
		return $this->middle_name;
	}

	/**
	 * Get the [last_name] column value.
	 * 
	 * @return     string
	 */
	public function getLastName()
	{
		return $this->last_name;
	}

	/**
	 * Get the [address_line1] column value.
	 * 
	 * @return     string
	 */
	public function getAddressLine1()
	{
		return $this->address_line1;
	}

	/**
	 * Get the [address_line2] column value.
	 * 
	 * @return     string
	 */
	public function getAddressLine2()
	{
		return $this->address_line2;
	}

	/**
	 * Get the [city] column value.
	 * 
	 * @return     string
	 */
	public function getCity()
	{
		return $this->city;
	}

	/**
	 * Get the [state] column value.
	 * 
	 * @return     string
	 */
	public function getState()
	{
		return $this->state;
	}

	/**
	 * Get the [zip] column value.
	 * 
	 * @return     string
	 */
	public function getZip()
	{
		return $this->zip;
	}

	/**
	 * Get the [country] column value.
	 * 
	 * @return     string
	 */
	public function getCountry()
	{
		return $this->country;
	}

	/**
	 * Get the [phone] column value.
	 * 
	 * @return     string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [workshop_id] column value.
	 * 
	 * @return     int
	 */
	public function getWorkshopId()
	{
		return $this->workshop_id;
	}

	/**
	 * Get the [optionally formatted] temporal [conf_email_sent_to_client_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getConfEmailSentToClientAt($format = 'Y-m-d H:i:s')
	{
		if ($this->conf_email_sent_to_client_at === null) {
			return null;
		}


		if ($this->conf_email_sent_to_client_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->conf_email_sent_to_client_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->conf_email_sent_to_client_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [cookie_name] column value.
	 * 
	 * @return     string
	 */
	public function getCookieName()
	{
		return $this->cookie_name;
	}

	/**
	 * Get the [cookie_value] column value.
	 * 
	 * @return     string
	 */
	public function getCookieValue()
	{
		return $this->cookie_value;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RegistrantPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->first_name !== $v) {
			$this->first_name = $v;
			$this->modifiedColumns[] = RegistrantPeer::FIRST_NAME;
		}

		return $this;
	} // setFirstName()

	/**
	 * Set the value of [middle_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setMiddleName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->middle_name !== $v) {
			$this->middle_name = $v;
			$this->modifiedColumns[] = RegistrantPeer::MIDDLE_NAME;
		}

		return $this;
	} // setMiddleName()

	/**
	 * Set the value of [last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->last_name !== $v) {
			$this->last_name = $v;
			$this->modifiedColumns[] = RegistrantPeer::LAST_NAME;
		}

		return $this;
	} // setLastName()

	/**
	 * Set the value of [address_line1] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setAddressLine1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_line1 !== $v) {
			$this->address_line1 = $v;
			$this->modifiedColumns[] = RegistrantPeer::ADDRESS_LINE1;
		}

		return $this;
	} // setAddressLine1()

	/**
	 * Set the value of [address_line2] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setAddressLine2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_line2 !== $v) {
			$this->address_line2 = $v;
			$this->modifiedColumns[] = RegistrantPeer::ADDRESS_LINE2;
		}

		return $this;
	} // setAddressLine2()

	/**
	 * Set the value of [city] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setCity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->city !== $v) {
			$this->city = $v;
			$this->modifiedColumns[] = RegistrantPeer::CITY;
		}

		return $this;
	} // setCity()

	/**
	 * Set the value of [state] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setState($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->state !== $v) {
			$this->state = $v;
			$this->modifiedColumns[] = RegistrantPeer::STATE;
		}

		return $this;
	} // setState()

	/**
	 * Set the value of [zip] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setZip($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip !== $v) {
			$this->zip = $v;
			$this->modifiedColumns[] = RegistrantPeer::ZIP;
		}

		return $this;
	} // setZip()

	/**
	 * Set the value of [country] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setCountry($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->country !== $v) {
			$this->country = $v;
			$this->modifiedColumns[] = RegistrantPeer::COUNTRY;
		}

		return $this;
	} // setCountry()

	/**
	 * Set the value of [phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->phone !== $v) {
			$this->phone = $v;
			$this->modifiedColumns[] = RegistrantPeer::PHONE;
		}

		return $this;
	} // setPhone()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = RegistrantPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [workshop_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setWorkshopId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->workshop_id !== $v) {
			$this->workshop_id = $v;
			$this->modifiedColumns[] = RegistrantPeer::WORKSHOP_ID;
		}

		if ($this->aWorkshop !== null && $this->aWorkshop->getId() !== $v) {
			$this->aWorkshop = null;
		}

		return $this;
	} // setWorkshopId()

	/**
	 * Sets the value of [conf_email_sent_to_client_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setConfEmailSentToClientAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->conf_email_sent_to_client_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->conf_email_sent_to_client_at !== null && $tmpDt = new DateTime($this->conf_email_sent_to_client_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->conf_email_sent_to_client_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RegistrantPeer::CONF_EMAIL_SENT_TO_CLIENT_AT;
			}
		} // if either are not null

		return $this;
	} // setConfEmailSentToClientAt()

	/**
	 * Set the value of [cookie_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setCookieName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cookie_name !== $v) {
			$this->cookie_name = $v;
			$this->modifiedColumns[] = RegistrantPeer::COOKIE_NAME;
		}

		return $this;
	} // setCookieName()

	/**
	 * Set the value of [cookie_value] column.
	 * 
	 * @param      string $v new value
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setCookieValue($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cookie_value !== $v) {
			$this->cookie_value = $v;
			$this->modifiedColumns[] = RegistrantPeer::COOKIE_VALUE;
		}

		return $this;
	} // setCookieValue()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Registrant The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RegistrantPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->first_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->middle_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->last_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->address_line1 = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->address_line2 = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->city = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->state = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->zip = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->country = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->phone = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->email = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->workshop_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->conf_email_sent_to_client_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->cookie_name = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->cookie_value = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->created_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = RegistrantPeer::NUM_COLUMNS - RegistrantPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Registrant object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aWorkshop !== null && $this->workshop_id !== $this->aWorkshop->getId()) {
			$this->aWorkshop = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RegistrantPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RegistrantPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aWorkshop = null;
			$this->collRegistrantExtras = null;
			$this->lastRegistrantExtraCriteria = null;

			$this->collWorkshopRegistrants = null;
			$this->lastWorkshopRegistrantCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RegistrantPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRegistrant:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				RegistrantPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRegistrant:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RegistrantPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRegistrant:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(RegistrantPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRegistrant:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				RegistrantPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aWorkshop !== null) {
				if ($this->aWorkshop->isModified() || $this->aWorkshop->isNew()) {
					$affectedRows += $this->aWorkshop->save($con);
				}
				$this->setWorkshop($this->aWorkshop);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RegistrantPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RegistrantPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RegistrantPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collRegistrantExtras !== null) {
				foreach ($this->collRegistrantExtras as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collWorkshopRegistrants !== null) {
				foreach ($this->collWorkshopRegistrants as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aWorkshop !== null) {
				if (!$this->aWorkshop->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aWorkshop->getValidationFailures());
				}
			}


			if (($retval = RegistrantPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collRegistrantExtras !== null) {
					foreach ($this->collRegistrantExtras as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collWorkshopRegistrants !== null) {
					foreach ($this->collWorkshopRegistrants as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RegistrantPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getFirstName();
				break;
			case 2:
				return $this->getMiddleName();
				break;
			case 3:
				return $this->getLastName();
				break;
			case 4:
				return $this->getAddressLine1();
				break;
			case 5:
				return $this->getAddressLine2();
				break;
			case 6:
				return $this->getCity();
				break;
			case 7:
				return $this->getState();
				break;
			case 8:
				return $this->getZip();
				break;
			case 9:
				return $this->getCountry();
				break;
			case 10:
				return $this->getPhone();
				break;
			case 11:
				return $this->getEmail();
				break;
			case 12:
				return $this->getWorkshopId();
				break;
			case 13:
				return $this->getConfEmailSentToClientAt();
				break;
			case 14:
				return $this->getCookieName();
				break;
			case 15:
				return $this->getCookieValue();
				break;
			case 16:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RegistrantPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getFirstName(),
			$keys[2] => $this->getMiddleName(),
			$keys[3] => $this->getLastName(),
			$keys[4] => $this->getAddressLine1(),
			$keys[5] => $this->getAddressLine2(),
			$keys[6] => $this->getCity(),
			$keys[7] => $this->getState(),
			$keys[8] => $this->getZip(),
			$keys[9] => $this->getCountry(),
			$keys[10] => $this->getPhone(),
			$keys[11] => $this->getEmail(),
			$keys[12] => $this->getWorkshopId(),
			$keys[13] => $this->getConfEmailSentToClientAt(),
			$keys[14] => $this->getCookieName(),
			$keys[15] => $this->getCookieValue(),
			$keys[16] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RegistrantPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setFirstName($value);
				break;
			case 2:
				$this->setMiddleName($value);
				break;
			case 3:
				$this->setLastName($value);
				break;
			case 4:
				$this->setAddressLine1($value);
				break;
			case 5:
				$this->setAddressLine2($value);
				break;
			case 6:
				$this->setCity($value);
				break;
			case 7:
				$this->setState($value);
				break;
			case 8:
				$this->setZip($value);
				break;
			case 9:
				$this->setCountry($value);
				break;
			case 10:
				$this->setPhone($value);
				break;
			case 11:
				$this->setEmail($value);
				break;
			case 12:
				$this->setWorkshopId($value);
				break;
			case 13:
				$this->setConfEmailSentToClientAt($value);
				break;
			case 14:
				$this->setCookieName($value);
				break;
			case 15:
				$this->setCookieValue($value);
				break;
			case 16:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RegistrantPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFirstName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setMiddleName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLastName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAddressLine1($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setAddressLine2($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCity($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setState($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setZip($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCountry($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setPhone($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setEmail($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setWorkshopId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setConfEmailSentToClientAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCookieName($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCookieValue($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setCreatedAt($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);

		if ($this->isColumnModified(RegistrantPeer::ID)) $criteria->add(RegistrantPeer::ID, $this->id);
		if ($this->isColumnModified(RegistrantPeer::FIRST_NAME)) $criteria->add(RegistrantPeer::FIRST_NAME, $this->first_name);
		if ($this->isColumnModified(RegistrantPeer::MIDDLE_NAME)) $criteria->add(RegistrantPeer::MIDDLE_NAME, $this->middle_name);
		if ($this->isColumnModified(RegistrantPeer::LAST_NAME)) $criteria->add(RegistrantPeer::LAST_NAME, $this->last_name);
		if ($this->isColumnModified(RegistrantPeer::ADDRESS_LINE1)) $criteria->add(RegistrantPeer::ADDRESS_LINE1, $this->address_line1);
		if ($this->isColumnModified(RegistrantPeer::ADDRESS_LINE2)) $criteria->add(RegistrantPeer::ADDRESS_LINE2, $this->address_line2);
		if ($this->isColumnModified(RegistrantPeer::CITY)) $criteria->add(RegistrantPeer::CITY, $this->city);
		if ($this->isColumnModified(RegistrantPeer::STATE)) $criteria->add(RegistrantPeer::STATE, $this->state);
		if ($this->isColumnModified(RegistrantPeer::ZIP)) $criteria->add(RegistrantPeer::ZIP, $this->zip);
		if ($this->isColumnModified(RegistrantPeer::COUNTRY)) $criteria->add(RegistrantPeer::COUNTRY, $this->country);
		if ($this->isColumnModified(RegistrantPeer::PHONE)) $criteria->add(RegistrantPeer::PHONE, $this->phone);
		if ($this->isColumnModified(RegistrantPeer::EMAIL)) $criteria->add(RegistrantPeer::EMAIL, $this->email);
		if ($this->isColumnModified(RegistrantPeer::WORKSHOP_ID)) $criteria->add(RegistrantPeer::WORKSHOP_ID, $this->workshop_id);
		if ($this->isColumnModified(RegistrantPeer::CONF_EMAIL_SENT_TO_CLIENT_AT)) $criteria->add(RegistrantPeer::CONF_EMAIL_SENT_TO_CLIENT_AT, $this->conf_email_sent_to_client_at);
		if ($this->isColumnModified(RegistrantPeer::COOKIE_NAME)) $criteria->add(RegistrantPeer::COOKIE_NAME, $this->cookie_name);
		if ($this->isColumnModified(RegistrantPeer::COOKIE_VALUE)) $criteria->add(RegistrantPeer::COOKIE_VALUE, $this->cookie_value);
		if ($this->isColumnModified(RegistrantPeer::CREATED_AT)) $criteria->add(RegistrantPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);

		$criteria->add(RegistrantPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Registrant (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFirstName($this->first_name);

		$copyObj->setMiddleName($this->middle_name);

		$copyObj->setLastName($this->last_name);

		$copyObj->setAddressLine1($this->address_line1);

		$copyObj->setAddressLine2($this->address_line2);

		$copyObj->setCity($this->city);

		$copyObj->setState($this->state);

		$copyObj->setZip($this->zip);

		$copyObj->setCountry($this->country);

		$copyObj->setPhone($this->phone);

		$copyObj->setEmail($this->email);

		$copyObj->setWorkshopId($this->workshop_id);

		$copyObj->setConfEmailSentToClientAt($this->conf_email_sent_to_client_at);

		$copyObj->setCookieName($this->cookie_name);

		$copyObj->setCookieValue($this->cookie_value);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getRegistrantExtras() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRegistrantExtra($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getWorkshopRegistrants() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addWorkshopRegistrant($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Registrant Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RegistrantPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RegistrantPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Workshop object.
	 *
	 * @param      Workshop $v
	 * @return     Registrant The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setWorkshop(Workshop $v = null)
	{
		if ($v === null) {
			$this->setWorkshopId(NULL);
		} else {
			$this->setWorkshopId($v->getId());
		}

		$this->aWorkshop = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Workshop object, it will not be re-added.
		if ($v !== null) {
			$v->addRegistrant($this);
		}

		return $this;
	}


	/**
	 * Get the associated Workshop object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Workshop The associated Workshop object.
	 * @throws     PropelException
	 */
	public function getWorkshop(PropelPDO $con = null)
	{
		if ($this->aWorkshop === null && ($this->workshop_id !== null)) {
			$this->aWorkshop = WorkshopPeer::retrieveByPk($this->workshop_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aWorkshop->addRegistrants($this);
			 */
		}
		return $this->aWorkshop;
	}

	/**
	 * Clears out the collRegistrantExtras collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRegistrantExtras()
	 */
	public function clearRegistrantExtras()
	{
		$this->collRegistrantExtras = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRegistrantExtras collection (array).
	 *
	 * By default this just sets the collRegistrantExtras collection to an empty array (like clearcollRegistrantExtras());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRegistrantExtras()
	{
		$this->collRegistrantExtras = array();
	}

	/**
	 * Gets an array of RegistrantExtra objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Registrant has previously been saved, it will retrieve
	 * related RegistrantExtras from storage. If this Registrant is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RegistrantExtra[]
	 * @throws     PropelException
	 */
	public function getRegistrantExtras($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRegistrantExtras === null) {
			if ($this->isNew()) {
			   $this->collRegistrantExtras = array();
			} else {

				$criteria->add(RegistrantExtraPeer::REGISTRANT_ID, $this->id);

				RegistrantExtraPeer::addSelectColumns($criteria);
				$this->collRegistrantExtras = RegistrantExtraPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RegistrantExtraPeer::REGISTRANT_ID, $this->id);

				RegistrantExtraPeer::addSelectColumns($criteria);
				if (!isset($this->lastRegistrantExtraCriteria) || !$this->lastRegistrantExtraCriteria->equals($criteria)) {
					$this->collRegistrantExtras = RegistrantExtraPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRegistrantExtraCriteria = $criteria;
		return $this->collRegistrantExtras;
	}

	/**
	 * Returns the number of related RegistrantExtra objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RegistrantExtra objects.
	 * @throws     PropelException
	 */
	public function countRegistrantExtras(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRegistrantExtras === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RegistrantExtraPeer::REGISTRANT_ID, $this->id);

				$count = RegistrantExtraPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RegistrantExtraPeer::REGISTRANT_ID, $this->id);

				if (!isset($this->lastRegistrantExtraCriteria) || !$this->lastRegistrantExtraCriteria->equals($criteria)) {
					$count = RegistrantExtraPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collRegistrantExtras);
				}
			} else {
				$count = count($this->collRegistrantExtras);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a RegistrantExtra object to this object
	 * through the RegistrantExtra foreign key attribute.
	 *
	 * @param      RegistrantExtra $l RegistrantExtra
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRegistrantExtra(RegistrantExtra $l)
	{
		if ($this->collRegistrantExtras === null) {
			$this->initRegistrantExtras();
		}
		if (!in_array($l, $this->collRegistrantExtras, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRegistrantExtras, $l);
			$l->setRegistrant($this);
		}
	}

	/**
	 * Clears out the collWorkshopRegistrants collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addWorkshopRegistrants()
	 */
	public function clearWorkshopRegistrants()
	{
		$this->collWorkshopRegistrants = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collWorkshopRegistrants collection (array).
	 *
	 * By default this just sets the collWorkshopRegistrants collection to an empty array (like clearcollWorkshopRegistrants());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initWorkshopRegistrants()
	{
		$this->collWorkshopRegistrants = array();
	}

	/**
	 * Gets an array of WorkshopRegistrant objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Registrant has previously been saved, it will retrieve
	 * related WorkshopRegistrants from storage. If this Registrant is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array WorkshopRegistrant[]
	 * @throws     PropelException
	 */
	public function getWorkshopRegistrants($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collWorkshopRegistrants === null) {
			if ($this->isNew()) {
			   $this->collWorkshopRegistrants = array();
			} else {

				$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

				WorkshopRegistrantPeer::addSelectColumns($criteria);
				$this->collWorkshopRegistrants = WorkshopRegistrantPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

				WorkshopRegistrantPeer::addSelectColumns($criteria);
				if (!isset($this->lastWorkshopRegistrantCriteria) || !$this->lastWorkshopRegistrantCriteria->equals($criteria)) {
					$this->collWorkshopRegistrants = WorkshopRegistrantPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastWorkshopRegistrantCriteria = $criteria;
		return $this->collWorkshopRegistrants;
	}

	/**
	 * Returns the number of related WorkshopRegistrant objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related WorkshopRegistrant objects.
	 * @throws     PropelException
	 */
	public function countWorkshopRegistrants(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collWorkshopRegistrants === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

				$count = WorkshopRegistrantPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

				if (!isset($this->lastWorkshopRegistrantCriteria) || !$this->lastWorkshopRegistrantCriteria->equals($criteria)) {
					$count = WorkshopRegistrantPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collWorkshopRegistrants);
				}
			} else {
				$count = count($this->collWorkshopRegistrants);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a WorkshopRegistrant object to this object
	 * through the WorkshopRegistrant foreign key attribute.
	 *
	 * @param      WorkshopRegistrant $l WorkshopRegistrant
	 * @return     void
	 * @throws     PropelException
	 */
	public function addWorkshopRegistrant(WorkshopRegistrant $l)
	{
		if ($this->collWorkshopRegistrants === null) {
			$this->initWorkshopRegistrants();
		}
		if (!in_array($l, $this->collWorkshopRegistrants, true)) { // only add it if the **same** object is not already associated
			array_push($this->collWorkshopRegistrants, $l);
			$l->setRegistrant($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Registrant is new, it will return
	 * an empty collection; or if this Registrant has previously
	 * been saved, it will retrieve related WorkshopRegistrants from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Registrant.
	 */
	public function getWorkshopRegistrantsJoinWorkshop($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RegistrantPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collWorkshopRegistrants === null) {
			if ($this->isNew()) {
				$this->collWorkshopRegistrants = array();
			} else {

				$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

				$this->collWorkshopRegistrants = WorkshopRegistrantPeer::doSelectJoinWorkshop($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(WorkshopRegistrantPeer::REGISTRANT_ID, $this->id);

			if (!isset($this->lastWorkshopRegistrantCriteria) || !$this->lastWorkshopRegistrantCriteria->equals($criteria)) {
				$this->collWorkshopRegistrants = WorkshopRegistrantPeer::doSelectJoinWorkshop($criteria, $con, $join_behavior);
			}
		}
		$this->lastWorkshopRegistrantCriteria = $criteria;

		return $this->collWorkshopRegistrants;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collRegistrantExtras) {
				foreach ((array) $this->collRegistrantExtras as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collWorkshopRegistrants) {
				foreach ((array) $this->collWorkshopRegistrants as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collRegistrantExtras = null;
		$this->collWorkshopRegistrants = null;
			$this->aWorkshop = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseRegistrant:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseRegistrant::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseRegistrant
