<?php

/**
 * Base static class for performing query and update operations on the 'profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Nov 11 20:46:56 2011
 *
 * @package    lib.model.om
 */
abstract class BaseProfilePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'profile';

	/** the related Propel class for this table */
	const OM_CLASS = 'Profile';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Profile';

	/** the related TableMap class for this table */
	const TM_CLASS = 'ProfileTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 40;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'profile.ID';

	/** the column name for the FULL_NAME field */
	const FULL_NAME = 'profile.FULL_NAME';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'profile.FIRST_NAME';

	/** the column name for the MIDDLE_NAME field */
	const MIDDLE_NAME = 'profile.MIDDLE_NAME';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'profile.LAST_NAME';

	/** the column name for the ADDRESS1 field */
	const ADDRESS1 = 'profile.ADDRESS1';

	/** the column name for the ADDRESS2 field */
	const ADDRESS2 = 'profile.ADDRESS2';

	/** the column name for the CITY field */
	const CITY = 'profile.CITY';

	/** the column name for the STATE_PROV field */
	const STATE_PROV = 'profile.STATE_PROV';

	/** the column name for the ZIP_POSTCODE field */
	const ZIP_POSTCODE = 'profile.ZIP_POSTCODE';

	/** the column name for the COUNTRY field */
	const COUNTRY = 'profile.COUNTRY';

	/** the column name for the TELEPHONE1 field */
	const TELEPHONE1 = 'profile.TELEPHONE1';

	/** the column name for the TELEPHONE2 field */
	const TELEPHONE2 = 'profile.TELEPHONE2';

	/** the column name for the EMAIL1 field */
	const EMAIL1 = 'profile.EMAIL1';

	/** the column name for the EMAIL2 field */
	const EMAIL2 = 'profile.EMAIL2';

	/** the column name for the GENDER field */
	const GENDER = 'profile.GENDER';

	/** the column name for the AGE field */
	const AGE = 'profile.AGE';

	/** the column name for the SECRET field */
	const SECRET = 'profile.SECRET';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'profile.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'profile.UPDATED_AT';

	/** the column name for the EXTRA1 field */
	const EXTRA1 = 'profile.EXTRA1';

	/** the column name for the EXTRA2 field */
	const EXTRA2 = 'profile.EXTRA2';

	/** the column name for the EXTRA3 field */
	const EXTRA3 = 'profile.EXTRA3';

	/** the column name for the EXTRA4 field */
	const EXTRA4 = 'profile.EXTRA4';

	/** the column name for the EXTRA5 field */
	const EXTRA5 = 'profile.EXTRA5';

	/** the column name for the EXTRA6 field */
	const EXTRA6 = 'profile.EXTRA6';

	/** the column name for the EXTRA7 field */
	const EXTRA7 = 'profile.EXTRA7';

	/** the column name for the EXTRA8 field */
	const EXTRA8 = 'profile.EXTRA8';

	/** the column name for the EXTRA9 field */
	const EXTRA9 = 'profile.EXTRA9';

	/** the column name for the EXTRA10 field */
	const EXTRA10 = 'profile.EXTRA10';

	/** the column name for the EXTRA11 field */
	const EXTRA11 = 'profile.EXTRA11';

	/** the column name for the EXTRA12 field */
	const EXTRA12 = 'profile.EXTRA12';

	/** the column name for the EXTRA13 field */
	const EXTRA13 = 'profile.EXTRA13';

	/** the column name for the EXTRA14 field */
	const EXTRA14 = 'profile.EXTRA14';

	/** the column name for the EXTRA15 field */
	const EXTRA15 = 'profile.EXTRA15';

	/** the column name for the EXTRA16 field */
	const EXTRA16 = 'profile.EXTRA16';

	/** the column name for the EXTRA17 field */
	const EXTRA17 = 'profile.EXTRA17';

	/** the column name for the EXTRA18 field */
	const EXTRA18 = 'profile.EXTRA18';

	/** the column name for the EXTRA19 field */
	const EXTRA19 = 'profile.EXTRA19';

	/** the column name for the EXTRA20 field */
	const EXTRA20 = 'profile.EXTRA20';

	/**
	 * An identiy map to hold any loaded instances of Profile objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Profile[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'FullName', 'FirstName', 'MiddleName', 'LastName', 'Address1', 'Address2', 'City', 'StateProv', 'ZipPostcode', 'Country', 'Telephone1', 'Telephone2', 'Email1', 'Email2', 'Gender', 'Age', 'Secret', 'CreatedAt', 'UpdatedAt', 'Extra1', 'Extra2', 'Extra3', 'Extra4', 'Extra5', 'Extra6', 'Extra7', 'Extra8', 'Extra9', 'Extra10', 'Extra11', 'Extra12', 'Extra13', 'Extra14', 'Extra15', 'Extra16', 'Extra17', 'Extra18', 'Extra19', 'Extra20', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'fullName', 'firstName', 'middleName', 'lastName', 'address1', 'address2', 'city', 'stateProv', 'zipPostcode', 'country', 'telephone1', 'telephone2', 'email1', 'email2', 'gender', 'age', 'secret', 'createdAt', 'updatedAt', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::FULL_NAME, self::FIRST_NAME, self::MIDDLE_NAME, self::LAST_NAME, self::ADDRESS1, self::ADDRESS2, self::CITY, self::STATE_PROV, self::ZIP_POSTCODE, self::COUNTRY, self::TELEPHONE1, self::TELEPHONE2, self::EMAIL1, self::EMAIL2, self::GENDER, self::AGE, self::SECRET, self::CREATED_AT, self::UPDATED_AT, self::EXTRA1, self::EXTRA2, self::EXTRA3, self::EXTRA4, self::EXTRA5, self::EXTRA6, self::EXTRA7, self::EXTRA8, self::EXTRA9, self::EXTRA10, self::EXTRA11, self::EXTRA12, self::EXTRA13, self::EXTRA14, self::EXTRA15, self::EXTRA16, self::EXTRA17, self::EXTRA18, self::EXTRA19, self::EXTRA20, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'full_name', 'first_name', 'middle_name', 'last_name', 'address1', 'address2', 'city', 'state_prov', 'zip_postcode', 'country', 'telephone1', 'telephone2', 'email1', 'email2', 'gender', 'age', 'secret', 'created_at', 'updated_at', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'FullName' => 1, 'FirstName' => 2, 'MiddleName' => 3, 'LastName' => 4, 'Address1' => 5, 'Address2' => 6, 'City' => 7, 'StateProv' => 8, 'ZipPostcode' => 9, 'Country' => 10, 'Telephone1' => 11, 'Telephone2' => 12, 'Email1' => 13, 'Email2' => 14, 'Gender' => 15, 'Age' => 16, 'Secret' => 17, 'CreatedAt' => 18, 'UpdatedAt' => 19, 'Extra1' => 20, 'Extra2' => 21, 'Extra3' => 22, 'Extra4' => 23, 'Extra5' => 24, 'Extra6' => 25, 'Extra7' => 26, 'Extra8' => 27, 'Extra9' => 28, 'Extra10' => 29, 'Extra11' => 30, 'Extra12' => 31, 'Extra13' => 32, 'Extra14' => 33, 'Extra15' => 34, 'Extra16' => 35, 'Extra17' => 36, 'Extra18' => 37, 'Extra19' => 38, 'Extra20' => 39, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'fullName' => 1, 'firstName' => 2, 'middleName' => 3, 'lastName' => 4, 'address1' => 5, 'address2' => 6, 'city' => 7, 'stateProv' => 8, 'zipPostcode' => 9, 'country' => 10, 'telephone1' => 11, 'telephone2' => 12, 'email1' => 13, 'email2' => 14, 'gender' => 15, 'age' => 16, 'secret' => 17, 'createdAt' => 18, 'updatedAt' => 19, 'extra1' => 20, 'extra2' => 21, 'extra3' => 22, 'extra4' => 23, 'extra5' => 24, 'extra6' => 25, 'extra7' => 26, 'extra8' => 27, 'extra9' => 28, 'extra10' => 29, 'extra11' => 30, 'extra12' => 31, 'extra13' => 32, 'extra14' => 33, 'extra15' => 34, 'extra16' => 35, 'extra17' => 36, 'extra18' => 37, 'extra19' => 38, 'extra20' => 39, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::FULL_NAME => 1, self::FIRST_NAME => 2, self::MIDDLE_NAME => 3, self::LAST_NAME => 4, self::ADDRESS1 => 5, self::ADDRESS2 => 6, self::CITY => 7, self::STATE_PROV => 8, self::ZIP_POSTCODE => 9, self::COUNTRY => 10, self::TELEPHONE1 => 11, self::TELEPHONE2 => 12, self::EMAIL1 => 13, self::EMAIL2 => 14, self::GENDER => 15, self::AGE => 16, self::SECRET => 17, self::CREATED_AT => 18, self::UPDATED_AT => 19, self::EXTRA1 => 20, self::EXTRA2 => 21, self::EXTRA3 => 22, self::EXTRA4 => 23, self::EXTRA5 => 24, self::EXTRA6 => 25, self::EXTRA7 => 26, self::EXTRA8 => 27, self::EXTRA9 => 28, self::EXTRA10 => 29, self::EXTRA11 => 30, self::EXTRA12 => 31, self::EXTRA13 => 32, self::EXTRA14 => 33, self::EXTRA15 => 34, self::EXTRA16 => 35, self::EXTRA17 => 36, self::EXTRA18 => 37, self::EXTRA19 => 38, self::EXTRA20 => 39, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'full_name' => 1, 'first_name' => 2, 'middle_name' => 3, 'last_name' => 4, 'address1' => 5, 'address2' => 6, 'city' => 7, 'state_prov' => 8, 'zip_postcode' => 9, 'country' => 10, 'telephone1' => 11, 'telephone2' => 12, 'email1' => 13, 'email2' => 14, 'gender' => 15, 'age' => 16, 'secret' => 17, 'created_at' => 18, 'updated_at' => 19, 'extra1' => 20, 'extra2' => 21, 'extra3' => 22, 'extra4' => 23, 'extra5' => 24, 'extra6' => 25, 'extra7' => 26, 'extra8' => 27, 'extra9' => 28, 'extra10' => 29, 'extra11' => 30, 'extra12' => 31, 'extra13' => 32, 'extra14' => 33, 'extra15' => 34, 'extra16' => 35, 'extra17' => 36, 'extra18' => 37, 'extra19' => 38, 'extra20' => 39, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ProfilePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ProfilePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(ProfilePeer::ID);
		$criteria->addSelectColumn(ProfilePeer::FULL_NAME);
		$criteria->addSelectColumn(ProfilePeer::FIRST_NAME);
		$criteria->addSelectColumn(ProfilePeer::MIDDLE_NAME);
		$criteria->addSelectColumn(ProfilePeer::LAST_NAME);
		$criteria->addSelectColumn(ProfilePeer::ADDRESS1);
		$criteria->addSelectColumn(ProfilePeer::ADDRESS2);
		$criteria->addSelectColumn(ProfilePeer::CITY);
		$criteria->addSelectColumn(ProfilePeer::STATE_PROV);
		$criteria->addSelectColumn(ProfilePeer::ZIP_POSTCODE);
		$criteria->addSelectColumn(ProfilePeer::COUNTRY);
		$criteria->addSelectColumn(ProfilePeer::TELEPHONE1);
		$criteria->addSelectColumn(ProfilePeer::TELEPHONE2);
		$criteria->addSelectColumn(ProfilePeer::EMAIL1);
		$criteria->addSelectColumn(ProfilePeer::EMAIL2);
		$criteria->addSelectColumn(ProfilePeer::GENDER);
		$criteria->addSelectColumn(ProfilePeer::AGE);
		$criteria->addSelectColumn(ProfilePeer::SECRET);
		$criteria->addSelectColumn(ProfilePeer::CREATED_AT);
		$criteria->addSelectColumn(ProfilePeer::UPDATED_AT);
		$criteria->addSelectColumn(ProfilePeer::EXTRA1);
		$criteria->addSelectColumn(ProfilePeer::EXTRA2);
		$criteria->addSelectColumn(ProfilePeer::EXTRA3);
		$criteria->addSelectColumn(ProfilePeer::EXTRA4);
		$criteria->addSelectColumn(ProfilePeer::EXTRA5);
		$criteria->addSelectColumn(ProfilePeer::EXTRA6);
		$criteria->addSelectColumn(ProfilePeer::EXTRA7);
		$criteria->addSelectColumn(ProfilePeer::EXTRA8);
		$criteria->addSelectColumn(ProfilePeer::EXTRA9);
		$criteria->addSelectColumn(ProfilePeer::EXTRA10);
		$criteria->addSelectColumn(ProfilePeer::EXTRA11);
		$criteria->addSelectColumn(ProfilePeer::EXTRA12);
		$criteria->addSelectColumn(ProfilePeer::EXTRA13);
		$criteria->addSelectColumn(ProfilePeer::EXTRA14);
		$criteria->addSelectColumn(ProfilePeer::EXTRA15);
		$criteria->addSelectColumn(ProfilePeer::EXTRA16);
		$criteria->addSelectColumn(ProfilePeer::EXTRA17);
		$criteria->addSelectColumn(ProfilePeer::EXTRA18);
		$criteria->addSelectColumn(ProfilePeer::EXTRA19);
		$criteria->addSelectColumn(ProfilePeer::EXTRA20);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ProfilePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ProfilePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseProfilePeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Profile
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ProfilePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ProfilePeer::populateObjects(ProfilePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ProfilePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseProfilePeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Profile $value A Profile object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Profile $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Profile object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Profile) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Profile object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Profile Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to profile
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
		// invalidate objects in TribeParticipantPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		TribeParticipantPeer::clearInstancePool();

		// invalidate objects in ProgramQuestionnairePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		ProgramQuestionnairePeer::clearInstancePool();

		// invalidate objects in DietaryPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		DietaryPeer::clearInstancePool();

		// invalidate objects in CertificationPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		CertificationPeer::clearInstancePool();

		// invalidate objects in PodParticipantPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		PodParticipantPeer::clearInstancePool();

		// invalidate objects in AnnualQuestionnairePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		AnnualQuestionnairePeer::clearInstancePool();

		// invalidate objects in MedicalPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		MedicalPeer::clearInstancePool();

	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ProfilePeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ProfilePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ProfilePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ProfilePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseProfilePeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseProfilePeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new ProfileTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? ProfilePeer::CLASS_DEFAULT : ProfilePeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Profile or Criteria object.
	 *
	 * @param      mixed $values Criteria or Profile object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseProfilePeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseProfilePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Profile object
		}

		if ($criteria->containsKey(ProfilePeer::ID) && $criteria->keyContainsValue(ProfilePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ProfilePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseProfilePeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseProfilePeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Profile or Criteria object.
	 *
	 * @param      mixed $values Criteria or Profile object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseProfilePeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseProfilePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ProfilePeer::ID);
			$selectCriteria->add(ProfilePeer::ID, $criteria->remove(ProfilePeer::ID), $comparison);

		} else { // $values is Profile object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseProfilePeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseProfilePeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the profile table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ProfilePeer::doOnDeleteCascade(new Criteria(ProfilePeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(ProfilePeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			ProfilePeer::clearInstancePool();
			ProfilePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Profile or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Profile object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Profile) { // it's a model object
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ProfilePeer::ID, (array) $values, Criteria::IN);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += ProfilePeer::doOnDeleteCascade($criteria, $con);
			
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			if ($values instanceof Criteria) {
				ProfilePeer::clearInstancePool();
			} elseif ($values instanceof Profile) { // it's a model object
				ProfilePeer::removeInstanceFromPool($values);
			} else { // it's a primary key, or an array of pks
				foreach ((array) $values as $singleval) {
					ProfilePeer::removeInstanceFromPool($singleval);
				}
			}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			ProfilePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = ProfilePeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related TribeParticipant objects
			$criteria = new Criteria(TribeParticipantPeer::DATABASE_NAME);
			
			$criteria->add(TribeParticipantPeer::PROFILE_ID, $obj->getId());
			$affectedRows += TribeParticipantPeer::doDelete($criteria, $con);

			// delete related ProgramQuestionnaire objects
			$criteria = new Criteria(ProgramQuestionnairePeer::DATABASE_NAME);
			
			$criteria->add(ProgramQuestionnairePeer::PROFILE_ID, $obj->getId());
			$affectedRows += ProgramQuestionnairePeer::doDelete($criteria, $con);

			// delete related Dietary objects
			$criteria = new Criteria(DietaryPeer::DATABASE_NAME);
			
			$criteria->add(DietaryPeer::PROFILE_ID, $obj->getId());
			$affectedRows += DietaryPeer::doDelete($criteria, $con);

			// delete related Certification objects
			$criteria = new Criteria(CertificationPeer::DATABASE_NAME);
			
			$criteria->add(CertificationPeer::PROFILE_ID, $obj->getId());
			$affectedRows += CertificationPeer::doDelete($criteria, $con);

			// delete related PodParticipant objects
			$criteria = new Criteria(PodParticipantPeer::DATABASE_NAME);
			
			$criteria->add(PodParticipantPeer::PROFILE_ID, $obj->getId());
			$affectedRows += PodParticipantPeer::doDelete($criteria, $con);

			// delete related AnnualQuestionnaire objects
			$criteria = new Criteria(AnnualQuestionnairePeer::DATABASE_NAME);
			
			$criteria->add(AnnualQuestionnairePeer::PROFILE_ID, $obj->getId());
			$affectedRows += AnnualQuestionnairePeer::doDelete($criteria, $con);

			// delete related Medical objects
			$criteria = new Criteria(MedicalPeer::DATABASE_NAME);
			
			$criteria->add(MedicalPeer::PROFILE_ID, $obj->getId());
			$affectedRows += MedicalPeer::doDelete($criteria, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given Profile object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Profile $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Profile $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ProfilePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ProfilePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(ProfilePeer::DATABASE_NAME, ProfilePeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Profile
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ProfilePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ProfilePeer::DATABASE_NAME);
		$criteria->add(ProfilePeer::ID, $pk);

		$v = ProfilePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ProfilePeer::DATABASE_NAME);
			$criteria->add(ProfilePeer::ID, $pks, Criteria::IN);
			$objs = ProfilePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseProfilePeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseProfilePeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseProfilePeer::buildTableMap();

