<?php

/**
 * Base static class for performing query and update operations on the 'annual_questionnaire' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Nov 11 20:46:59 2011
 *
 * @package    lib.model.om
 */
abstract class BaseAnnualQuestionnairePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'annual_questionnaire';

	/** the related Propel class for this table */
	const OM_CLASS = 'AnnualQuestionnaire';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.AnnualQuestionnaire';

	/** the related TableMap class for this table */
	const TM_CLASS = 'AnnualQuestionnaireTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 33;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'annual_questionnaire.ID';

	/** the column name for the PROFILE_ID field */
	const PROFILE_ID = 'annual_questionnaire.PROFILE_ID';

	/** the column name for the TRIBE_FIRST_CHOICE field */
	const TRIBE_FIRST_CHOICE = 'annual_questionnaire.TRIBE_FIRST_CHOICE';

	/** the column name for the TRIBE_SECOND_CHOICE field */
	const TRIBE_SECOND_CHOICE = 'annual_questionnaire.TRIBE_SECOND_CHOICE';

	/** the column name for the I_AM_TYPE field */
	const I_AM_TYPE = 'annual_questionnaire.I_AM_TYPE';

	/** the column name for the YOUR_TRIBE_NAME field */
	const YOUR_TRIBE_NAME = 'annual_questionnaire.YOUR_TRIBE_NAME';

	/** the column name for the YOUR_TRIBE_LEADER1 field */
	const YOUR_TRIBE_LEADER1 = 'annual_questionnaire.YOUR_TRIBE_LEADER1';

	/** the column name for the YOUR_TRIBE_LEADER2 field */
	const YOUR_TRIBE_LEADER2 = 'annual_questionnaire.YOUR_TRIBE_LEADER2';

	/** the column name for the ANYTHING_ELSE field */
	const ANYTHING_ELSE = 'annual_questionnaire.ANYTHING_ELSE';

	/** the column name for the CONTACT_TELEPHONE field */
	const CONTACT_TELEPHONE = 'annual_questionnaire.CONTACT_TELEPHONE';

	/** the column name for the CONTACT_EMAIL field */
	const CONTACT_EMAIL = 'annual_questionnaire.CONTACT_EMAIL';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'annual_questionnaire.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'annual_questionnaire.UPDATED_AT';

	/** the column name for the EXTRA1 field */
	const EXTRA1 = 'annual_questionnaire.EXTRA1';

	/** the column name for the EXTRA2 field */
	const EXTRA2 = 'annual_questionnaire.EXTRA2';

	/** the column name for the EXTRA3 field */
	const EXTRA3 = 'annual_questionnaire.EXTRA3';

	/** the column name for the EXTRA4 field */
	const EXTRA4 = 'annual_questionnaire.EXTRA4';

	/** the column name for the EXTRA5 field */
	const EXTRA5 = 'annual_questionnaire.EXTRA5';

	/** the column name for the EXTRA6 field */
	const EXTRA6 = 'annual_questionnaire.EXTRA6';

	/** the column name for the EXTRA7 field */
	const EXTRA7 = 'annual_questionnaire.EXTRA7';

	/** the column name for the EXTRA8 field */
	const EXTRA8 = 'annual_questionnaire.EXTRA8';

	/** the column name for the EXTRA9 field */
	const EXTRA9 = 'annual_questionnaire.EXTRA9';

	/** the column name for the EXTRA10 field */
	const EXTRA10 = 'annual_questionnaire.EXTRA10';

	/** the column name for the EXTRA11 field */
	const EXTRA11 = 'annual_questionnaire.EXTRA11';

	/** the column name for the EXTRA12 field */
	const EXTRA12 = 'annual_questionnaire.EXTRA12';

	/** the column name for the EXTRA13 field */
	const EXTRA13 = 'annual_questionnaire.EXTRA13';

	/** the column name for the EXTRA14 field */
	const EXTRA14 = 'annual_questionnaire.EXTRA14';

	/** the column name for the EXTRA15 field */
	const EXTRA15 = 'annual_questionnaire.EXTRA15';

	/** the column name for the EXTRA16 field */
	const EXTRA16 = 'annual_questionnaire.EXTRA16';

	/** the column name for the EXTRA17 field */
	const EXTRA17 = 'annual_questionnaire.EXTRA17';

	/** the column name for the EXTRA18 field */
	const EXTRA18 = 'annual_questionnaire.EXTRA18';

	/** the column name for the EXTRA19 field */
	const EXTRA19 = 'annual_questionnaire.EXTRA19';

	/** the column name for the EXTRA20 field */
	const EXTRA20 = 'annual_questionnaire.EXTRA20';

	/**
	 * An identiy map to hold any loaded instances of AnnualQuestionnaire objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array AnnualQuestionnaire[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'ProfileId', 'TribeFirstChoice', 'TribeSecondChoice', 'IAmType', 'YourTribeName', 'YourTribeLeader1', 'YourTribeLeader2', 'AnythingElse', 'ContactTelephone', 'ContactEmail', 'CreatedAt', 'UpdatedAt', 'Extra1', 'Extra2', 'Extra3', 'Extra4', 'Extra5', 'Extra6', 'Extra7', 'Extra8', 'Extra9', 'Extra10', 'Extra11', 'Extra12', 'Extra13', 'Extra14', 'Extra15', 'Extra16', 'Extra17', 'Extra18', 'Extra19', 'Extra20', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'profileId', 'tribeFirstChoice', 'tribeSecondChoice', 'iAmType', 'yourTribeName', 'yourTribeLeader1', 'yourTribeLeader2', 'anythingElse', 'contactTelephone', 'contactEmail', 'createdAt', 'updatedAt', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::PROFILE_ID, self::TRIBE_FIRST_CHOICE, self::TRIBE_SECOND_CHOICE, self::I_AM_TYPE, self::YOUR_TRIBE_NAME, self::YOUR_TRIBE_LEADER1, self::YOUR_TRIBE_LEADER2, self::ANYTHING_ELSE, self::CONTACT_TELEPHONE, self::CONTACT_EMAIL, self::CREATED_AT, self::UPDATED_AT, self::EXTRA1, self::EXTRA2, self::EXTRA3, self::EXTRA4, self::EXTRA5, self::EXTRA6, self::EXTRA7, self::EXTRA8, self::EXTRA9, self::EXTRA10, self::EXTRA11, self::EXTRA12, self::EXTRA13, self::EXTRA14, self::EXTRA15, self::EXTRA16, self::EXTRA17, self::EXTRA18, self::EXTRA19, self::EXTRA20, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'profile_id', 'tribe_first_choice', 'tribe_second_choice', 'i_am_type', 'your_tribe_name', 'your_tribe_leader1', 'your_tribe_leader2', 'anything_else', 'contact_telephone', 'contact_email', 'created_at', 'updated_at', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'ProfileId' => 1, 'TribeFirstChoice' => 2, 'TribeSecondChoice' => 3, 'IAmType' => 4, 'YourTribeName' => 5, 'YourTribeLeader1' => 6, 'YourTribeLeader2' => 7, 'AnythingElse' => 8, 'ContactTelephone' => 9, 'ContactEmail' => 10, 'CreatedAt' => 11, 'UpdatedAt' => 12, 'Extra1' => 13, 'Extra2' => 14, 'Extra3' => 15, 'Extra4' => 16, 'Extra5' => 17, 'Extra6' => 18, 'Extra7' => 19, 'Extra8' => 20, 'Extra9' => 21, 'Extra10' => 22, 'Extra11' => 23, 'Extra12' => 24, 'Extra13' => 25, 'Extra14' => 26, 'Extra15' => 27, 'Extra16' => 28, 'Extra17' => 29, 'Extra18' => 30, 'Extra19' => 31, 'Extra20' => 32, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'profileId' => 1, 'tribeFirstChoice' => 2, 'tribeSecondChoice' => 3, 'iAmType' => 4, 'yourTribeName' => 5, 'yourTribeLeader1' => 6, 'yourTribeLeader2' => 7, 'anythingElse' => 8, 'contactTelephone' => 9, 'contactEmail' => 10, 'createdAt' => 11, 'updatedAt' => 12, 'extra1' => 13, 'extra2' => 14, 'extra3' => 15, 'extra4' => 16, 'extra5' => 17, 'extra6' => 18, 'extra7' => 19, 'extra8' => 20, 'extra9' => 21, 'extra10' => 22, 'extra11' => 23, 'extra12' => 24, 'extra13' => 25, 'extra14' => 26, 'extra15' => 27, 'extra16' => 28, 'extra17' => 29, 'extra18' => 30, 'extra19' => 31, 'extra20' => 32, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::PROFILE_ID => 1, self::TRIBE_FIRST_CHOICE => 2, self::TRIBE_SECOND_CHOICE => 3, self::I_AM_TYPE => 4, self::YOUR_TRIBE_NAME => 5, self::YOUR_TRIBE_LEADER1 => 6, self::YOUR_TRIBE_LEADER2 => 7, self::ANYTHING_ELSE => 8, self::CONTACT_TELEPHONE => 9, self::CONTACT_EMAIL => 10, self::CREATED_AT => 11, self::UPDATED_AT => 12, self::EXTRA1 => 13, self::EXTRA2 => 14, self::EXTRA3 => 15, self::EXTRA4 => 16, self::EXTRA5 => 17, self::EXTRA6 => 18, self::EXTRA7 => 19, self::EXTRA8 => 20, self::EXTRA9 => 21, self::EXTRA10 => 22, self::EXTRA11 => 23, self::EXTRA12 => 24, self::EXTRA13 => 25, self::EXTRA14 => 26, self::EXTRA15 => 27, self::EXTRA16 => 28, self::EXTRA17 => 29, self::EXTRA18 => 30, self::EXTRA19 => 31, self::EXTRA20 => 32, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'profile_id' => 1, 'tribe_first_choice' => 2, 'tribe_second_choice' => 3, 'i_am_type' => 4, 'your_tribe_name' => 5, 'your_tribe_leader1' => 6, 'your_tribe_leader2' => 7, 'anything_else' => 8, 'contact_telephone' => 9, 'contact_email' => 10, 'created_at' => 11, 'updated_at' => 12, 'extra1' => 13, 'extra2' => 14, 'extra3' => 15, 'extra4' => 16, 'extra5' => 17, 'extra6' => 18, 'extra7' => 19, 'extra8' => 20, 'extra9' => 21, 'extra10' => 22, 'extra11' => 23, 'extra12' => 24, 'extra13' => 25, 'extra14' => 26, 'extra15' => 27, 'extra16' => 28, 'extra17' => 29, 'extra18' => 30, 'extra19' => 31, 'extra20' => 32, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AnnualQuestionnairePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AnnualQuestionnairePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(AnnualQuestionnairePeer::ID);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::PROFILE_ID);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::TRIBE_FIRST_CHOICE);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::TRIBE_SECOND_CHOICE);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::I_AM_TYPE);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::YOUR_TRIBE_NAME);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::YOUR_TRIBE_LEADER1);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::YOUR_TRIBE_LEADER2);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::ANYTHING_ELSE);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::CONTACT_TELEPHONE);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::CONTACT_EMAIL);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::CREATED_AT);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::UPDATED_AT);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA1);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA2);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA3);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA4);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA5);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA6);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA7);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA8);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA9);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA10);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA11);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA12);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA13);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA14);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA15);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA16);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA17);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA18);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA19);
		$criteria->addSelectColumn(AnnualQuestionnairePeer::EXTRA20);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AnnualQuestionnairePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AnnualQuestionnairePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     AnnualQuestionnaire
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AnnualQuestionnairePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AnnualQuestionnairePeer::populateObjects(AnnualQuestionnairePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AnnualQuestionnairePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      AnnualQuestionnaire $value A AnnualQuestionnaire object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(AnnualQuestionnaire $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A AnnualQuestionnaire object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof AnnualQuestionnaire) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or AnnualQuestionnaire object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     AnnualQuestionnaire Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to annual_questionnaire
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AnnualQuestionnairePeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AnnualQuestionnairePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AnnualQuestionnairePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AnnualQuestionnairePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Profile table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinProfile(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AnnualQuestionnairePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AnnualQuestionnairePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AnnualQuestionnairePeer::PROFILE_ID, ProfilePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of AnnualQuestionnaire objects pre-filled with their Profile objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AnnualQuestionnaire objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinProfile(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AnnualQuestionnairePeer::addSelectColumns($criteria);
		$startcol = (AnnualQuestionnairePeer::NUM_COLUMNS - AnnualQuestionnairePeer::NUM_LAZY_LOAD_COLUMNS);
		ProfilePeer::addSelectColumns($criteria);

		$criteria->addJoin(AnnualQuestionnairePeer::PROFILE_ID, ProfilePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AnnualQuestionnairePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AnnualQuestionnairePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AnnualQuestionnairePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AnnualQuestionnairePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ProfilePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ProfilePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = ProfilePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ProfilePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (AnnualQuestionnaire) to $obj2 (Profile)
				$obj2->addAnnualQuestionnaire($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AnnualQuestionnairePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AnnualQuestionnairePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AnnualQuestionnairePeer::PROFILE_ID, ProfilePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of AnnualQuestionnaire objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AnnualQuestionnaire objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AnnualQuestionnairePeer::addSelectColumns($criteria);
		$startcol2 = (AnnualQuestionnairePeer::NUM_COLUMNS - AnnualQuestionnairePeer::NUM_LAZY_LOAD_COLUMNS);

		ProfilePeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (ProfilePeer::NUM_COLUMNS - ProfilePeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AnnualQuestionnairePeer::PROFILE_ID, ProfilePeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AnnualQuestionnairePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AnnualQuestionnairePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AnnualQuestionnairePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AnnualQuestionnairePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Profile rows

			$key2 = ProfilePeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = ProfilePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = ProfilePeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ProfilePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (AnnualQuestionnaire) to the collection in $obj2 (Profile)
				$obj2->addAnnualQuestionnaire($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseAnnualQuestionnairePeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseAnnualQuestionnairePeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new AnnualQuestionnaireTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? AnnualQuestionnairePeer::CLASS_DEFAULT : AnnualQuestionnairePeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a AnnualQuestionnaire or Criteria object.
	 *
	 * @param      mixed $values Criteria or AnnualQuestionnaire object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnnualQuestionnairePeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from AnnualQuestionnaire object
		}

		if ($criteria->containsKey(AnnualQuestionnairePeer::ID) && $criteria->keyContainsValue(AnnualQuestionnairePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AnnualQuestionnairePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnnualQuestionnairePeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a AnnualQuestionnaire or Criteria object.
	 *
	 * @param      mixed $values Criteria or AnnualQuestionnaire object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnnualQuestionnairePeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AnnualQuestionnairePeer::ID);
			$selectCriteria->add(AnnualQuestionnairePeer::ID, $criteria->remove(AnnualQuestionnairePeer::ID), $comparison);

		} else { // $values is AnnualQuestionnaire object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseAnnualQuestionnairePeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseAnnualQuestionnairePeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the annual_questionnaire table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AnnualQuestionnairePeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			AnnualQuestionnairePeer::clearInstancePool();
			AnnualQuestionnairePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a AnnualQuestionnaire or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or AnnualQuestionnaire object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AnnualQuestionnairePeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof AnnualQuestionnaire) { // it's a model object
			// invalidate the cache for this single object
			AnnualQuestionnairePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AnnualQuestionnairePeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				AnnualQuestionnairePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			AnnualQuestionnairePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given AnnualQuestionnaire object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      AnnualQuestionnaire $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(AnnualQuestionnaire $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AnnualQuestionnairePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AnnualQuestionnairePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(AnnualQuestionnairePeer::DATABASE_NAME, AnnualQuestionnairePeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     AnnualQuestionnaire
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AnnualQuestionnairePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AnnualQuestionnairePeer::DATABASE_NAME);
		$criteria->add(AnnualQuestionnairePeer::ID, $pk);

		$v = AnnualQuestionnairePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AnnualQuestionnairePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AnnualQuestionnairePeer::DATABASE_NAME);
			$criteria->add(AnnualQuestionnairePeer::ID, $pks, Criteria::IN);
			$objs = AnnualQuestionnairePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseAnnualQuestionnairePeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseAnnualQuestionnairePeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseAnnualQuestionnairePeer::buildTableMap();

