<?php

/**
 * Execcoach filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 */
abstract class BaseExeccoachFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'profile_id'              => new sfWidgetFormPropelChoice(array('model' => 'Profile', 'add_empty' => true)),
      'created_at'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'updated_at'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'bio_resume'              => new sfWidgetFormFilterInput(),
      'photo'                   => new sfWidgetFormFilterInput(),
      'home_country'            => new sfWidgetFormFilterInput(),
      'phone_home'              => new sfWidgetFormFilterInput(),
      'phone_office'            => new sfWidgetFormFilterInput(),
      'phone_mobile'            => new sfWidgetFormFilterInput(),
      'skype'                   => new sfWidgetFormFilterInput(),
      'time_zone'               => new sfWidgetFormFilterInput(),
      'language_fluency'        => new sfWidgetFormFilterInput(),
      'education'               => new sfWidgetFormFilterInput(),
      'certifications'          => new sfWidgetFormFilterInput(),
      'authorized_to_work'      => new sfWidgetFormFilterInput(),
      'years_cti'               => new sfWidgetFormFilterInput(),
      'what_capacity'           => new sfWidgetFormFilterInput(),
      'corporate_clients'       => new sfWidgetFormFilterInput(),
      'training_style'          => new sfWidgetFormFilterInput(),
      'publication_engagements' => new sfWidgetFormFilterInput(),
      'expertise'               => new sfWidgetFormFilterInput(),
      'industries'              => new sfWidgetFormFilterInput(),
      'types_of_coaching'       => new sfWidgetFormFilterInput(),
      'number_of_executives'    => new sfWidgetFormFilterInput(),
      'outcomes_tracked'        => new sfWidgetFormFilterInput(),
      'work_visa'               => new sfWidgetFormFilterInput(),
      'travel_visa'             => new sfWidgetFormFilterInput(),
      'media_exposure'          => new sfWidgetFormFilterInput(),
      'size_of_group'           => new sfWidgetFormFilterInput(),
      'endorsements'            => new sfWidgetFormFilterInput(),
      'utilization_corp_forl'   => new sfWidgetFormFilterInput(),
      'utilization_corp_coach'  => new sfWidgetFormFilterInput(),
      'utilization_exec_coach'  => new sfWidgetFormFilterInput(),
      'extra1'                  => new sfWidgetFormFilterInput(),
      'extra2'                  => new sfWidgetFormFilterInput(),
      'extra3'                  => new sfWidgetFormFilterInput(),
      'extra4'                  => new sfWidgetFormFilterInput(),
      'extra5'                  => new sfWidgetFormFilterInput(),
      'extra6'                  => new sfWidgetFormFilterInput(),
      'extra7'                  => new sfWidgetFormFilterInput(),
      'extra8'                  => new sfWidgetFormFilterInput(),
      'extra9'                  => new sfWidgetFormFilterInput(),
      'extra10'                 => new sfWidgetFormFilterInput(),
      'extra11'                 => new sfWidgetFormFilterInput(),
      'extra12'                 => new sfWidgetFormFilterInput(),
      'extra13'                 => new sfWidgetFormFilterInput(),
      'extra14'                 => new sfWidgetFormFilterInput(),
      'extra15'                 => new sfWidgetFormFilterInput(),
      'extra16'                 => new sfWidgetFormFilterInput(),
      'extra17'                 => new sfWidgetFormFilterInput(),
      'extra18'                 => new sfWidgetFormFilterInput(),
      'extra19'                 => new sfWidgetFormFilterInput(),
      'extra20'                 => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'profile_id'              => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Profile', 'column' => 'id')),
      'created_at'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'updated_at'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'bio_resume'              => new sfValidatorPass(array('required' => false)),
      'photo'                   => new sfValidatorPass(array('required' => false)),
      'home_country'            => new sfValidatorPass(array('required' => false)),
      'phone_home'              => new sfValidatorPass(array('required' => false)),
      'phone_office'            => new sfValidatorPass(array('required' => false)),
      'phone_mobile'            => new sfValidatorPass(array('required' => false)),
      'skype'                   => new sfValidatorPass(array('required' => false)),
      'time_zone'               => new sfValidatorPass(array('required' => false)),
      'language_fluency'        => new sfValidatorPass(array('required' => false)),
      'education'               => new sfValidatorPass(array('required' => false)),
      'certifications'          => new sfValidatorPass(array('required' => false)),
      'authorized_to_work'      => new sfValidatorPass(array('required' => false)),
      'years_cti'               => new sfValidatorPass(array('required' => false)),
      'what_capacity'           => new sfValidatorPass(array('required' => false)),
      'corporate_clients'       => new sfValidatorPass(array('required' => false)),
      'training_style'          => new sfValidatorPass(array('required' => false)),
      'publication_engagements' => new sfValidatorPass(array('required' => false)),
      'expertise'               => new sfValidatorPass(array('required' => false)),
      'industries'              => new sfValidatorPass(array('required' => false)),
      'types_of_coaching'       => new sfValidatorPass(array('required' => false)),
      'number_of_executives'    => new sfValidatorPass(array('required' => false)),
      'outcomes_tracked'        => new sfValidatorPass(array('required' => false)),
      'work_visa'               => new sfValidatorPass(array('required' => false)),
      'travel_visa'             => new sfValidatorPass(array('required' => false)),
      'media_exposure'          => new sfValidatorPass(array('required' => false)),
      'size_of_group'           => new sfValidatorPass(array('required' => false)),
      'endorsements'            => new sfValidatorPass(array('required' => false)),
      'utilization_corp_forl'   => new sfValidatorPass(array('required' => false)),
      'utilization_corp_coach'  => new sfValidatorPass(array('required' => false)),
      'utilization_exec_coach'  => new sfValidatorPass(array('required' => false)),
      'extra1'                  => new sfValidatorPass(array('required' => false)),
      'extra2'                  => new sfValidatorPass(array('required' => false)),
      'extra3'                  => new sfValidatorPass(array('required' => false)),
      'extra4'                  => new sfValidatorPass(array('required' => false)),
      'extra5'                  => new sfValidatorPass(array('required' => false)),
      'extra6'                  => new sfValidatorPass(array('required' => false)),
      'extra7'                  => new sfValidatorPass(array('required' => false)),
      'extra8'                  => new sfValidatorPass(array('required' => false)),
      'extra9'                  => new sfValidatorPass(array('required' => false)),
      'extra10'                 => new sfValidatorPass(array('required' => false)),
      'extra11'                 => new sfValidatorPass(array('required' => false)),
      'extra12'                 => new sfValidatorPass(array('required' => false)),
      'extra13'                 => new sfValidatorPass(array('required' => false)),
      'extra14'                 => new sfValidatorPass(array('required' => false)),
      'extra15'                 => new sfValidatorPass(array('required' => false)),
      'extra16'                 => new sfValidatorPass(array('required' => false)),
      'extra17'                 => new sfValidatorPass(array('required' => false)),
      'extra18'                 => new sfValidatorPass(array('required' => false)),
      'extra19'                 => new sfValidatorPass(array('required' => false)),
      'extra20'                 => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('execcoach_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Execcoach';
  }

  public function getFields()
  {
    return array(
      'id'                      => 'Number',
      'profile_id'              => 'ForeignKey',
      'created_at'              => 'Date',
      'updated_at'              => 'Date',
      'bio_resume'              => 'Text',
      'photo'                   => 'Text',
      'home_country'            => 'Text',
      'phone_home'              => 'Text',
      'phone_office'            => 'Text',
      'phone_mobile'            => 'Text',
      'skype'                   => 'Text',
      'time_zone'               => 'Text',
      'language_fluency'        => 'Text',
      'education'               => 'Text',
      'certifications'          => 'Text',
      'authorized_to_work'      => 'Text',
      'years_cti'               => 'Text',
      'what_capacity'           => 'Text',
      'corporate_clients'       => 'Text',
      'training_style'          => 'Text',
      'publication_engagements' => 'Text',
      'expertise'               => 'Text',
      'industries'              => 'Text',
      'types_of_coaching'       => 'Text',
      'number_of_executives'    => 'Text',
      'outcomes_tracked'        => 'Text',
      'work_visa'               => 'Text',
      'travel_visa'             => 'Text',
      'media_exposure'          => 'Text',
      'size_of_group'           => 'Text',
      'endorsements'            => 'Text',
      'utilization_corp_forl'   => 'Text',
      'utilization_corp_coach'  => 'Text',
      'utilization_exec_coach'  => 'Text',
      'extra1'                  => 'Text',
      'extra2'                  => 'Text',
      'extra3'                  => 'Text',
      'extra4'                  => 'Text',
      'extra5'                  => 'Text',
      'extra6'                  => 'Text',
      'extra7'                  => 'Text',
      'extra8'                  => 'Text',
      'extra9'                  => 'Text',
      'extra10'                 => 'Text',
      'extra11'                 => 'Text',
      'extra12'                 => 'Text',
      'extra13'                 => 'Text',
      'extra14'                 => 'Text',
      'extra15'                 => 'Text',
      'extra16'                 => 'Text',
      'extra17'                 => 'Text',
      'extra18'                 => 'Text',
      'extra19'                 => 'Text',
      'extra20'                 => 'Text',
    );
  }
}
