<?php

/**
 * Medical filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 */
abstract class BaseMedicalFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'profile_id'                  => new sfWidgetFormPropelChoice(array('model' => 'Profile', 'add_empty' => true)),
      'height'                      => new sfWidgetFormFilterInput(),
      'weight'                      => new sfWidgetFormFilterInput(),
      'conditions_physical'         => new sfWidgetFormFilterInput(),
      'conditions_psychological'    => new sfWidgetFormFilterInput(),
      'accommodations'              => new sfWidgetFormFilterInput(),
      'head'                        => new sfWidgetFormFilterInput(),
      'neck'                        => new sfWidgetFormFilterInput(),
      'whiplash'                    => new sfWidgetFormFilterInput(),
      'shoulders'                   => new sfWidgetFormFilterInput(),
      'arms'                        => new sfWidgetFormFilterInput(),
      'wrists'                      => new sfWidgetFormFilterInput(),
      'hands'                       => new sfWidgetFormFilterInput(),
      'upper_back'                  => new sfWidgetFormFilterInput(),
      'lower_back'                  => new sfWidgetFormFilterInput(),
      'pelvis'                      => new sfWidgetFormFilterInput(),
      'groin'                       => new sfWidgetFormFilterInput(),
      'dislocations'                => new sfWidgetFormFilterInput(),
      'dislocations_where'          => new sfWidgetFormFilterInput(),
      'asthma'                      => new sfWidgetFormFilterInput(),
      'do_you_smoke'                => new sfWidgetFormFilterInput(),
      'have_you_ever_smoked'        => new sfWidgetFormFilterInput(),
      'are_you_currently_pregnant'  => new sfWidgetFormFilterInput(),
      'due_date'                    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'lower_legs'                  => new sfWidgetFormFilterInput(),
      'thighs'                      => new sfWidgetFormFilterInput(),
      'knees'                       => new sfWidgetFormFilterInput(),
      'ankles'                      => new sfWidgetFormFilterInput(),
      'feet'                        => new sfWidgetFormFilterInput(),
      'internal_organs'             => new sfWidgetFormFilterInput(),
      'heart'                       => new sfWidgetFormFilterInput(),
      'lungs'                       => new sfWidgetFormFilterInput(),
      'ears'                        => new sfWidgetFormFilterInput(),
      'eyes'                        => new sfWidgetFormFilterInput(),
      'contact_lenses'              => new sfWidgetFormFilterInput(),
      'dizziness'                   => new sfWidgetFormFilterInput(),
      'high_blood_pressure'         => new sfWidgetFormFilterInput(),
      'heart_attack'                => new sfWidgetFormFilterInput(),
      'diabetes'                    => new sfWidgetFormFilterInput(),
      'epilepsy_seizures'           => new sfWidgetFormFilterInput(),
      'other_serious_illness'       => new sfWidgetFormFilterInput(),
      'explanation'                 => new sfWidgetFormFilterInput(),
      'allergies'                   => new sfWidgetFormFilterInput(),
      'medications'                 => new sfWidgetFormFilterInput(),
      'name_of_medications'         => new sfWidgetFormFilterInput(),
      'what_are_medications_for'    => new sfWidgetFormFilterInput(),
      'medication_dosages'          => new sfWidgetFormFilterInput(),
      'emergency_contact_name'      => new sfWidgetFormFilterInput(),
      'emergency_relationship'      => new sfWidgetFormFilterInput(),
      'emergency_address'           => new sfWidgetFormFilterInput(),
      'emergency_work_phone'        => new sfWidgetFormFilterInput(),
      'emergency_home_phone'        => new sfWidgetFormFilterInput(),
      'emergency_other_phone'       => new sfWidgetFormFilterInput(),
      'coverage_provider'           => new sfWidgetFormFilterInput(),
      'policy_number'               => new sfWidgetFormFilterInput(),
      'other_insurance_information' => new sfWidgetFormFilterInput(),
      'doctors_name'                => new sfWidgetFormFilterInput(),
      'doctors_contact_info'        => new sfWidgetFormFilterInput(),
      'release_of_liability'        => new sfWidgetFormFilterInput(),
      'created_at'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'updated_at'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'extra1'                      => new sfWidgetFormFilterInput(),
      'extra2'                      => new sfWidgetFormFilterInput(),
      'extra3'                      => new sfWidgetFormFilterInput(),
      'extra4'                      => new sfWidgetFormFilterInput(),
      'extra5'                      => new sfWidgetFormFilterInput(),
      'extra6'                      => new sfWidgetFormFilterInput(),
      'extra7'                      => new sfWidgetFormFilterInput(),
      'extra8'                      => new sfWidgetFormFilterInput(),
      'extra9'                      => new sfWidgetFormFilterInput(),
      'extra10'                     => new sfWidgetFormFilterInput(),
      'extra11'                     => new sfWidgetFormFilterInput(),
      'extra12'                     => new sfWidgetFormFilterInput(),
      'extra13'                     => new sfWidgetFormFilterInput(),
      'extra14'                     => new sfWidgetFormFilterInput(),
      'extra15'                     => new sfWidgetFormFilterInput(),
      'extra16'                     => new sfWidgetFormFilterInput(),
      'extra17'                     => new sfWidgetFormFilterInput(),
      'extra18'                     => new sfWidgetFormFilterInput(),
      'extra19'                     => new sfWidgetFormFilterInput(),
      'extra20'                     => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'profile_id'                  => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Profile', 'column' => 'id')),
      'height'                      => new sfValidatorPass(array('required' => false)),
      'weight'                      => new sfValidatorPass(array('required' => false)),
      'conditions_physical'         => new sfValidatorPass(array('required' => false)),
      'conditions_psychological'    => new sfValidatorPass(array('required' => false)),
      'accommodations'              => new sfValidatorPass(array('required' => false)),
      'head'                        => new sfValidatorPass(array('required' => false)),
      'neck'                        => new sfValidatorPass(array('required' => false)),
      'whiplash'                    => new sfValidatorPass(array('required' => false)),
      'shoulders'                   => new sfValidatorPass(array('required' => false)),
      'arms'                        => new sfValidatorPass(array('required' => false)),
      'wrists'                      => new sfValidatorPass(array('required' => false)),
      'hands'                       => new sfValidatorPass(array('required' => false)),
      'upper_back'                  => new sfValidatorPass(array('required' => false)),
      'lower_back'                  => new sfValidatorPass(array('required' => false)),
      'pelvis'                      => new sfValidatorPass(array('required' => false)),
      'groin'                       => new sfValidatorPass(array('required' => false)),
      'dislocations'                => new sfValidatorPass(array('required' => false)),
      'dislocations_where'          => new sfValidatorPass(array('required' => false)),
      'asthma'                      => new sfValidatorPass(array('required' => false)),
      'do_you_smoke'                => new sfValidatorPass(array('required' => false)),
      'have_you_ever_smoked'        => new sfValidatorPass(array('required' => false)),
      'are_you_currently_pregnant'  => new sfValidatorPass(array('required' => false)),
      'due_date'                    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'lower_legs'                  => new sfValidatorPass(array('required' => false)),
      'thighs'                      => new sfValidatorPass(array('required' => false)),
      'knees'                       => new sfValidatorPass(array('required' => false)),
      'ankles'                      => new sfValidatorPass(array('required' => false)),
      'feet'                        => new sfValidatorPass(array('required' => false)),
      'internal_organs'             => new sfValidatorPass(array('required' => false)),
      'heart'                       => new sfValidatorPass(array('required' => false)),
      'lungs'                       => new sfValidatorPass(array('required' => false)),
      'ears'                        => new sfValidatorPass(array('required' => false)),
      'eyes'                        => new sfValidatorPass(array('required' => false)),
      'contact_lenses'              => new sfValidatorPass(array('required' => false)),
      'dizziness'                   => new sfValidatorPass(array('required' => false)),
      'high_blood_pressure'         => new sfValidatorPass(array('required' => false)),
      'heart_attack'                => new sfValidatorPass(array('required' => false)),
      'diabetes'                    => new sfValidatorPass(array('required' => false)),
      'epilepsy_seizures'           => new sfValidatorPass(array('required' => false)),
      'other_serious_illness'       => new sfValidatorPass(array('required' => false)),
      'explanation'                 => new sfValidatorPass(array('required' => false)),
      'allergies'                   => new sfValidatorPass(array('required' => false)),
      'medications'                 => new sfValidatorPass(array('required' => false)),
      'name_of_medications'         => new sfValidatorPass(array('required' => false)),
      'what_are_medications_for'    => new sfValidatorPass(array('required' => false)),
      'medication_dosages'          => new sfValidatorPass(array('required' => false)),
      'emergency_contact_name'      => new sfValidatorPass(array('required' => false)),
      'emergency_relationship'      => new sfValidatorPass(array('required' => false)),
      'emergency_address'           => new sfValidatorPass(array('required' => false)),
      'emergency_work_phone'        => new sfValidatorPass(array('required' => false)),
      'emergency_home_phone'        => new sfValidatorPass(array('required' => false)),
      'emergency_other_phone'       => new sfValidatorPass(array('required' => false)),
      'coverage_provider'           => new sfValidatorPass(array('required' => false)),
      'policy_number'               => new sfValidatorPass(array('required' => false)),
      'other_insurance_information' => new sfValidatorPass(array('required' => false)),
      'doctors_name'                => new sfValidatorPass(array('required' => false)),
      'doctors_contact_info'        => new sfValidatorPass(array('required' => false)),
      'release_of_liability'        => new sfValidatorPass(array('required' => false)),
      'created_at'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'updated_at'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'extra1'                      => new sfValidatorPass(array('required' => false)),
      'extra2'                      => new sfValidatorPass(array('required' => false)),
      'extra3'                      => new sfValidatorPass(array('required' => false)),
      'extra4'                      => new sfValidatorPass(array('required' => false)),
      'extra5'                      => new sfValidatorPass(array('required' => false)),
      'extra6'                      => new sfValidatorPass(array('required' => false)),
      'extra7'                      => new sfValidatorPass(array('required' => false)),
      'extra8'                      => new sfValidatorPass(array('required' => false)),
      'extra9'                      => new sfValidatorPass(array('required' => false)),
      'extra10'                     => new sfValidatorPass(array('required' => false)),
      'extra11'                     => new sfValidatorPass(array('required' => false)),
      'extra12'                     => new sfValidatorPass(array('required' => false)),
      'extra13'                     => new sfValidatorPass(array('required' => false)),
      'extra14'                     => new sfValidatorPass(array('required' => false)),
      'extra15'                     => new sfValidatorPass(array('required' => false)),
      'extra16'                     => new sfValidatorPass(array('required' => false)),
      'extra17'                     => new sfValidatorPass(array('required' => false)),
      'extra18'                     => new sfValidatorPass(array('required' => false)),
      'extra19'                     => new sfValidatorPass(array('required' => false)),
      'extra20'                     => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('medical_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Medical';
  }

  public function getFields()
  {
    return array(
      'id'                          => 'Number',
      'profile_id'                  => 'ForeignKey',
      'height'                      => 'Text',
      'weight'                      => 'Text',
      'conditions_physical'         => 'Text',
      'conditions_psychological'    => 'Text',
      'accommodations'              => 'Text',
      'head'                        => 'Text',
      'neck'                        => 'Text',
      'whiplash'                    => 'Text',
      'shoulders'                   => 'Text',
      'arms'                        => 'Text',
      'wrists'                      => 'Text',
      'hands'                       => 'Text',
      'upper_back'                  => 'Text',
      'lower_back'                  => 'Text',
      'pelvis'                      => 'Text',
      'groin'                       => 'Text',
      'dislocations'                => 'Text',
      'dislocations_where'          => 'Text',
      'asthma'                      => 'Text',
      'do_you_smoke'                => 'Text',
      'have_you_ever_smoked'        => 'Text',
      'are_you_currently_pregnant'  => 'Text',
      'due_date'                    => 'Date',
      'lower_legs'                  => 'Text',
      'thighs'                      => 'Text',
      'knees'                       => 'Text',
      'ankles'                      => 'Text',
      'feet'                        => 'Text',
      'internal_organs'             => 'Text',
      'heart'                       => 'Text',
      'lungs'                       => 'Text',
      'ears'                        => 'Text',
      'eyes'                        => 'Text',
      'contact_lenses'              => 'Text',
      'dizziness'                   => 'Text',
      'high_blood_pressure'         => 'Text',
      'heart_attack'                => 'Text',
      'diabetes'                    => 'Text',
      'epilepsy_seizures'           => 'Text',
      'other_serious_illness'       => 'Text',
      'explanation'                 => 'Text',
      'allergies'                   => 'Text',
      'medications'                 => 'Text',
      'name_of_medications'         => 'Text',
      'what_are_medications_for'    => 'Text',
      'medication_dosages'          => 'Text',
      'emergency_contact_name'      => 'Text',
      'emergency_relationship'      => 'Text',
      'emergency_address'           => 'Text',
      'emergency_work_phone'        => 'Text',
      'emergency_home_phone'        => 'Text',
      'emergency_other_phone'       => 'Text',
      'coverage_provider'           => 'Text',
      'policy_number'               => 'Text',
      'other_insurance_information' => 'Text',
      'doctors_name'                => 'Text',
      'doctors_contact_info'        => 'Text',
      'release_of_liability'        => 'Text',
      'created_at'                  => 'Date',
      'updated_at'                  => 'Date',
      'extra1'                      => 'Text',
      'extra2'                      => 'Text',
      'extra3'                      => 'Text',
      'extra4'                      => 'Text',
      'extra5'                      => 'Text',
      'extra6'                      => 'Text',
      'extra7'                      => 'Text',
      'extra8'                      => 'Text',
      'extra9'                      => 'Text',
      'extra10'                     => 'Text',
      'extra11'                     => 'Text',
      'extra12'                     => 'Text',
      'extra13'                     => 'Text',
      'extra14'                     => 'Text',
      'extra15'                     => 'Text',
      'extra16'                     => 'Text',
      'extra17'                     => 'Text',
      'extra18'                     => 'Text',
      'extra19'                     => 'Text',
      'extra20'                     => 'Text',
    );
  }
}
