<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/29 23:59:10
sfConfig::add(array(
  'app_smtp_server_ip' => '127.0.0.1',
  'app_ctidatabase_server' => '184.73.210.4',
  'app_ctidatabase_port' => 3306,
  'app_ctidatabase_user' => 'c7user',
  'app_ctidatabase_password' => '8iKLo9',
  'app_remember_cookie_name' => 'scholarship_remember',
  'app_remember_key_expiration_age' => 864000,
  'app_webcomp_postkey' => 'fjgh15t',
  'app_webcomp_postkey2' => 'fjgh12fgt',
  'app_webcomp_baseurl' => 'http://webcomp.modelsmith.com/fmi-test/webcomp2_newFM',
  'app_webcomp_authen' => 'authenticate.php',
  'app_webcomp_recordexists' => 'abletogetrecord.php',
  'app_webcomp_newpw' => 'set_pw.php',
  'app_webcomp_commlog' => 'new_commlog.php',
));
