<?php

/**
 * ProgramQuestionnaire filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 */
abstract class BaseProgramQuestionnaireFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'profile_id'                  => new sfWidgetFormPropelChoice(array('model' => 'Profile', 'add_empty' => true)),
      'nationality'                 => new sfWidgetFormFilterInput(),
      'relationship_status'         => new sfWidgetFormFilterInput(),
      'current_profession'          => new sfWidgetFormFilterInput(),
      'past_profession'             => new sfWidgetFormFilterInput(),
      'personal_professional_goals' => new sfWidgetFormFilterInput(),
      'strengths'                   => new sfWidgetFormFilterInput(),
      'holds_you_back'              => new sfWidgetFormFilterInput(),
      'handle_failing'              => new sfWidgetFormFilterInput(),
      'willing_to_fail'             => new sfWidgetFormFilterInput(),
      'willing_to_listen'           => new sfWidgetFormFilterInput(),
      'therapy'                     => new sfWidgetFormFilterInput(),
      'therapy_details'             => new sfWidgetFormFilterInput(),
      'therapy_impact'              => new sfWidgetFormFilterInput(),
      'fundamentals'                => new sfWidgetFormFilterInput(),
      'intermediate_curriculum'     => new sfWidgetFormFilterInput(),
      'certification'               => new sfWidgetFormFilterInput(),
      'quest'                       => new sfWidgetFormFilterInput(),
      'icc_curriculum'              => new sfWidgetFormFilterInput(),
      'have_a_coach'                => new sfWidgetFormFilterInput(),
      'coaching_impact'             => new sfWidgetFormFilterInput(),
      'religious_affiliations'      => new sfWidgetFormFilterInput(),
      'religious_influences'        => new sfWidgetFormFilterInput(),
      'growth_experiences'          => new sfWidgetFormFilterInput(),
      'impact_as_a_leader'          => new sfWidgetFormFilterInput(),
      'challenge'                   => new sfWidgetFormFilterInput(),
      'why_this_program'            => new sfWidgetFormFilterInput(),
      'play_level'                  => new sfWidgetFormFilterInput(),
      'what_would_it_take'          => new sfWidgetFormFilterInput(),
      'bring_yourself_back'         => new sfWidgetFormFilterInput(),
      'going_the_distance'          => new sfWidgetFormFilterInput(),
      'i_was_born_to'               => new sfWidgetFormFilterInput(),
      'comments'                    => new sfWidgetFormFilterInput(),
      'created_at'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'updated_at'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'extra1'                      => new sfWidgetFormFilterInput(),
      'extra2'                      => new sfWidgetFormFilterInput(),
      'extra3'                      => new sfWidgetFormFilterInput(),
      'extra4'                      => new sfWidgetFormFilterInput(),
      'extra5'                      => new sfWidgetFormFilterInput(),
      'extra6'                      => new sfWidgetFormFilterInput(),
      'extra7'                      => new sfWidgetFormFilterInput(),
      'extra8'                      => new sfWidgetFormFilterInput(),
      'extra9'                      => new sfWidgetFormFilterInput(),
      'extra10'                     => new sfWidgetFormFilterInput(),
      'extra11'                     => new sfWidgetFormFilterInput(),
      'extra12'                     => new sfWidgetFormFilterInput(),
      'extra13'                     => new sfWidgetFormFilterInput(),
      'extra14'                     => new sfWidgetFormFilterInput(),
      'extra15'                     => new sfWidgetFormFilterInput(),
      'extra16'                     => new sfWidgetFormFilterInput(),
      'extra17'                     => new sfWidgetFormFilterInput(),
      'extra18'                     => new sfWidgetFormFilterInput(),
      'extra19'                     => new sfWidgetFormFilterInput(),
      'extra20'                     => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'profile_id'                  => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Profile', 'column' => 'id')),
      'nationality'                 => new sfValidatorPass(array('required' => false)),
      'relationship_status'         => new sfValidatorPass(array('required' => false)),
      'current_profession'          => new sfValidatorPass(array('required' => false)),
      'past_profession'             => new sfValidatorPass(array('required' => false)),
      'personal_professional_goals' => new sfValidatorPass(array('required' => false)),
      'strengths'                   => new sfValidatorPass(array('required' => false)),
      'holds_you_back'              => new sfValidatorPass(array('required' => false)),
      'handle_failing'              => new sfValidatorPass(array('required' => false)),
      'willing_to_fail'             => new sfValidatorPass(array('required' => false)),
      'willing_to_listen'           => new sfValidatorPass(array('required' => false)),
      'therapy'                     => new sfValidatorPass(array('required' => false)),
      'therapy_details'             => new sfValidatorPass(array('required' => false)),
      'therapy_impact'              => new sfValidatorPass(array('required' => false)),
      'fundamentals'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'intermediate_curriculum'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'certification'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'quest'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'icc_curriculum'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'have_a_coach'                => new sfValidatorPass(array('required' => false)),
      'coaching_impact'             => new sfValidatorPass(array('required' => false)),
      'religious_affiliations'      => new sfValidatorPass(array('required' => false)),
      'religious_influences'        => new sfValidatorPass(array('required' => false)),
      'growth_experiences'          => new sfValidatorPass(array('required' => false)),
      'impact_as_a_leader'          => new sfValidatorPass(array('required' => false)),
      'challenge'                   => new sfValidatorPass(array('required' => false)),
      'why_this_program'            => new sfValidatorPass(array('required' => false)),
      'play_level'                  => new sfValidatorPass(array('required' => false)),
      'what_would_it_take'          => new sfValidatorPass(array('required' => false)),
      'bring_yourself_back'         => new sfValidatorPass(array('required' => false)),
      'going_the_distance'          => new sfValidatorPass(array('required' => false)),
      'i_was_born_to'               => new sfValidatorPass(array('required' => false)),
      'comments'                    => new sfValidatorPass(array('required' => false)),
      'created_at'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'updated_at'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'extra1'                      => new sfValidatorPass(array('required' => false)),
      'extra2'                      => new sfValidatorPass(array('required' => false)),
      'extra3'                      => new sfValidatorPass(array('required' => false)),
      'extra4'                      => new sfValidatorPass(array('required' => false)),
      'extra5'                      => new sfValidatorPass(array('required' => false)),
      'extra6'                      => new sfValidatorPass(array('required' => false)),
      'extra7'                      => new sfValidatorPass(array('required' => false)),
      'extra8'                      => new sfValidatorPass(array('required' => false)),
      'extra9'                      => new sfValidatorPass(array('required' => false)),
      'extra10'                     => new sfValidatorPass(array('required' => false)),
      'extra11'                     => new sfValidatorPass(array('required' => false)),
      'extra12'                     => new sfValidatorPass(array('required' => false)),
      'extra13'                     => new sfValidatorPass(array('required' => false)),
      'extra14'                     => new sfValidatorPass(array('required' => false)),
      'extra15'                     => new sfValidatorPass(array('required' => false)),
      'extra16'                     => new sfValidatorPass(array('required' => false)),
      'extra17'                     => new sfValidatorPass(array('required' => false)),
      'extra18'                     => new sfValidatorPass(array('required' => false)),
      'extra19'                     => new sfValidatorPass(array('required' => false)),
      'extra20'                     => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('program_questionnaire_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'ProgramQuestionnaire';
  }

  public function getFields()
  {
    return array(
      'id'                          => 'Number',
      'profile_id'                  => 'ForeignKey',
      'nationality'                 => 'Text',
      'relationship_status'         => 'Text',
      'current_profession'          => 'Text',
      'past_profession'             => 'Text',
      'personal_professional_goals' => 'Text',
      'strengths'                   => 'Text',
      'holds_you_back'              => 'Text',
      'handle_failing'              => 'Text',
      'willing_to_fail'             => 'Text',
      'willing_to_listen'           => 'Text',
      'therapy'                     => 'Text',
      'therapy_details'             => 'Text',
      'therapy_impact'              => 'Text',
      'fundamentals'                => 'Number',
      'intermediate_curriculum'     => 'Number',
      'certification'               => 'Number',
      'quest'                       => 'Number',
      'icc_curriculum'              => 'Number',
      'have_a_coach'                => 'Text',
      'coaching_impact'             => 'Text',
      'religious_affiliations'      => 'Text',
      'religious_influences'        => 'Text',
      'growth_experiences'          => 'Text',
      'impact_as_a_leader'          => 'Text',
      'challenge'                   => 'Text',
      'why_this_program'            => 'Text',
      'play_level'                  => 'Text',
      'what_would_it_take'          => 'Text',
      'bring_yourself_back'         => 'Text',
      'going_the_distance'          => 'Text',
      'i_was_born_to'               => 'Text',
      'comments'                    => 'Text',
      'created_at'                  => 'Date',
      'updated_at'                  => 'Date',
      'extra1'                      => 'Text',
      'extra2'                      => 'Text',
      'extra3'                      => 'Text',
      'extra4'                      => 'Text',
      'extra5'                      => 'Text',
      'extra6'                      => 'Text',
      'extra7'                      => 'Text',
      'extra8'                      => 'Text',
      'extra9'                      => 'Text',
      'extra10'                     => 'Text',
      'extra11'                     => 'Text',
      'extra12'                     => 'Text',
      'extra13'                     => 'Text',
      'extra14'                     => 'Text',
      'extra15'                     => 'Text',
      'extra16'                     => 'Text',
      'extra17'                     => 'Text',
      'extra18'                     => 'Text',
      'extra19'                     => 'Text',
      'extra20'                     => 'Text',
    );
  }
}
