<?php use_helper('Object'); ?>
<!-- This file contains the CA Step 1 form           -->

  <div class="dabblePageContainer dabblePageNoNavigation">
    <div class="dabblePageLeftShadow">
      <div class="dabblePageRightShadow">
        <div class=
        "dabblePage dabblePageWithLogo dabbleSearchPage">
          <div class="dabblePageHeader" id="dabblePageTop">
            <div class="dabblePageLogo">
              <!--[if lte IE 6]><span style="display:block;width:176px;height:57px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/launchpad/images/logo250857176.png',sizingMethod='crop')"><![endif]--><img alt=""
              height="57" width="176" class="png24bit" src=
              "/launchpad/images/logo250857176.png" /> <!-- /publish/logo250857176.png -->
              <!--[if lte IE 6]></span><![endif]-->
            </div>

    <h1>&nbsp;</h1>

            <div id="dabblePageMenuLink" class=
            "dabblePageMobileOnly dabblePageNavigationLinks">
               
            </div>
          </div>

          <div id="dabblePageContent">

<?php echo form_tag('executivecoach/form1Process', 'method=post id=dabblePageForm  class=dabblePageForm name=dabblePageForm  enctype=multipart/form-data') ?>

                <input type="hidden" name="referer" value="<?php echo url_for("ctiforms/leadershipThankYou") ?>" />




<div class="dabblePageSection dabblePageSectionFull">
<div class="dabblePageColumn dabblePageColumn1">

<!--
<div class="dabblePageTextItem">
<div class="dabblePageText">
<p></p>
</div>
</div>
-->


<div class="dabblePageTextItem">
<div class="dabblePageText">
    <p>&nbsp;</p>
    <p>&nbsp;</p>

<h1>CTI Corporate Support</h1>



<p></p>

</div>
</div>


    <h1>Section A: Contact Info</h1>




<!-- ================= Generated by /Users/thomas/00-CTI/70-Exec-Coach-Tracking/iterate-fields.pl ================= -->

<!-- ================= TEXT INPUT: first_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="first_name">First Name</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="first_name" type="text" class="text" name="execcoach[first_name]" value="<?php echo $profile->getFirstName() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: last_name ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="last_name">Last Name</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="last_name" type="text" class="text" name="execcoach[last_name]" value="<?php echo $profile->getLastName() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_address1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address1">Address1</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_address1" type="text" class="text" name="execcoach[perm_address1]" value="<?php echo $profile->getPermAddress1() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_address2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_address2">Address2</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_address2" type="text" class="text" name="execcoach[perm_address2]" value="<?php echo $profile->getPermAddress2() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_city ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_city">City</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_city" type="text" class="text" name="execcoach[perm_city]" value="<?php echo $profile->getPermCity() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_state_prov ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_state_prov">State</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_state_prov" type="text" class="text" name="execcoach[perm_state_prov]" value="<?php echo $profile->getPermStateProv() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_zip_postcode ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_zip_postcode">Zip Code</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_zip_postcode" type="text" class="text" name="execcoach[perm_zip_postcode]" value="<?php echo $profile->getPermZipPostcode() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: perm_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="perm_country">Country</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="perm_country" type="text" class="text" name="execcoach[perm_country]" value="<?php echo $profile->getPermCountry() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: email1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="email1">Email Address</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="email1" type="text" class="text" name="execcoach[email1]" value="<?php echo $profile->getEmail1() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone1 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone1">Home Phone</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="telephone1" type="text" class="text" name="execcoach[telephone1]" value="<?php echo $profile->getTelephone1() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: phone_office ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="phone_office">Office Phone</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="phone_office" type="text" class="text" name="execcoach[phone_office]" value="<?php echo $exec->getPhoneOffice() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: telephone2 ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="telephone2">Mobile</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="telephone2" type="text" class="text" name="execcoach[telephone2]" value="<?php echo $profile->getTelephone1() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: skype ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="skype">Skype</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="skype" type="text" class="text" name="execcoach[skype]" value="<?php echo $exec->getSkype() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>









<h1>Section B: About You</h1>


<!-- ================= TEXTAREA: bio_resume ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="bio_resume">Attach an editable resume/bio. Include brief personal summary, professional background (company, years worked, title, brief description of role and accomplishments)</label>
       </div>
       <div class="dabblePageFormField">
<input type="file" id="bio_resume" name="bio_filename" />
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: photo ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
                                  <label for="photo">Current photo, preferably color, corporate head shot. Photo must be less than 1MB (1 megabyte) in size.</label>
   </div>
   <div class="dabblePageFormField ">
<input type="file" id="photo" name="photo_filename" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>












<!-- ================= TEXT INPUT: home_country ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="home_country">Home country  location</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="home_country" type="text" class="text" name="execcoach[home_country]" value="<?php echo $exec->getHomeCountry() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: time_zone ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="time_zone">Time zone</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="time_zone" type="text" class="text" name="execcoach[time_zone]" value="<?php echo $exec->getTimeZone() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: language_fluency ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="language_fluency">Language Fluency (fluency only)</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="language_fluency" type="text" class="text" name="execcoach[language_fluency]" value="<?php echo $exec->getLanguageFluency() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: education ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="education">Education</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="education" type="text" class="text" name="execcoach[education]" value="<?php echo $exec->getEducation() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: certifications ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="certifications">Certifications- ICF, CTI, assessment tools, etc.</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="certifications" cols="40" rows="4" name="execcoach[certifications]"><?php echo $exec->getCertifications() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: authorized_to_work ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="authorized_to_work">Authorized to work in which countries</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="authorized_to_work" cols="40" rows="4" name="execcoach[authorized_to_work]"><?php echo $exec->getAuthorizedToWork() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: years_cti ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="years_cti">Year began working with CTI</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="years_cti" type="text" class="text" name="execcoach[years_cti]" value="<?php echo $exec->getYearsCti() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: what_capacity ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="what_capacity">In what capacity</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="what_capacity" cols="40" rows="4" name="execcoach[what_capacity]"><?php echo $exec->getWhatCapacity() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: corporate_clients ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="corporate_clients">Corporate clients (company name only, up to 10)</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="corporate_clients" cols="40" rows="4" name="execcoach[corporate_clients]"><?php echo $exec->getCorporateClients() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: training_style ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="training_style">Coaching/Training style, philosophy</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="training_style" cols="40" rows="4" name="execcoach[training_style]"><?php echo $exec->getTrainingStyle() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: publication_engagements  ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="publication_engagements ">Publications? Articles? White papers? Workshops developed? Speaking engagements? Awards?</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="publication_engagements " cols="40" rows="4" name="execcoach[publication_engagements]"><?php echo $exec->getPublicationEngagements() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: expertise ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="expertise">Areas of expertise/specialty</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="expertise" cols="40" rows="4" name="execcoach[expertise]"><?php echo $exec->getExpertise() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: industries ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="industries">Industries best suited for</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="industries" cols="40" rows="4" name="execcoach[industries]"><?php echo $exec->getIndustries() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: types_of_coaching ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="types_of_coaching">Types of coaching and training engagements/sample projects</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="types_of_coaching" cols="40" rows="4" name="execcoach[types_of_coaching]"><?php echo $exec->getTypesOfCoaching() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: number_of_executives ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="number_of_executives">Number of executives coached (VP & up). Any C-suite?</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="number_of_executives" cols="40" rows="4" name="execcoach[number_of_executives]"><?php echo $exec->getNumberOfExecutives() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: outcomes_tracked ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="outcomes_tracked">Measurable outcomes tracked?</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="outcomes_tracked" cols="40" rows="4" name="execcoach[outcomes_tracked]"><?php echo $exec->getOutcomesTracked() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: work_visa ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="work_visa">Work visa (which countries)</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="work_visa" type="text" class="text" name="execcoach[work_visa]" value="<?php echo $exec->getWorkVisa() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: travel_visa ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="travel_visa">Travel visa (which countries)</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="travel_visa" type="text" class="text" name="execcoach[travel_visa]" value="<?php echo $exec->getTravelVisa() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: media_exposure ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="media_exposure">Media exposure (tv, radio, on-camera training videos, etc.)</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="media_exposure" cols="40" rows="4" name="execcoach[media_exposure]"><?php echo $exec->getMediaExposure() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: size_of_group ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="size_of_group">Size of group comfortable presenting to: (under 30, 31-75, 76-150, 151-300, 300plus)</label>
   </div>
   <div class="dabblePageFormField ">
      <input id="size_of_group" type="text" class="text" name="execcoach[size_of_group]" value="<?php echo $exec->getSizeOfGroup() ?>" />
   </div>
</div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXTAREA: endorsements ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="endorsements">Endorsements (from senior-level coachees, from speaking engagements, from corporate clients regarding your ability as a corporate FORL)</label>
       </div>
       <div class="dabblePageFormField">
           <textarea id="endorsements" cols="40" rows="4" name="execcoach[endorsements]"><?php echo $exec->getEndorsements() ?></textarea>
       </div>
   </div>
<div style="clear:both">&nbsp;</div>

<!-- ================= TEXT INPUT: utilization_corp_forl ================= -->
<div class= "dabblePageFormItem">
   <div class="dabblePageFormLabel">
      <label for="utilization_corp_forl">Where would you be bestutilized?<br /><br /></label>
   </div>
   <div class="dabblePageFormField checkboxes">
      <p><input id="utilization_corp_forl" type="checkbox" class="text" name="execcoach[utilization_corp_forl]" <?php echo $exec->getUtilizationCorpForl() == 'on' ? 'CHECKED' : '' ?> /> Corporate FORL</p>
  
      <p><input id="utilization_corp_coach" type="checkbox" class="text" name="execcoach[utilization_corp_coach]" <?php echo $exec->getUtilizationCorpCoach() == 'on' ? 'CHECKED' : '' ?> /> Corporate Coach</p>
  
      <p><input id="utilization_exec_coach" type="checkbox" class="text" name="execcoach[utilization_exec_coach]" <?php echo $exec->getUtilizationExecCoach() == 'on' ? 'CHECKED' : '' ?> /> Corporate Executive Coach</p>
   </div>
</div>

<!-- ================= TEXTAREA: date_submitted ================= -->
<div class= "dabblePageFormItem">
       <div class="dabblePageFormLabel">
           <label for="date_submitted">Date Submitted</label>
       </div>
       <div class="dabblePageFormField">
                                 <input id="date_submitted" type="text" class="text" name="execcoach[date_submitted]" value="<?php echo date('M j, Y') ?>" />
       </div>
   </div>
<div style="clear:both">&nbsp;</div>


<div style="clear:both">&nbsp;</div>
<div style="clear:both">&nbsp;</div>













<p class="qwed"></p>
             
                  <div class="dabblePageTextItem">
                    <div class="dabblePageText">
                      <p>
                      </em></p>

                    </div>
                  </div>
                </div>
              </div>

              <div class="clear"></div>

              <div class=
              "dabblePageSection dabblePageSectionFormActions">
                <div class="dabblePageColumn dabblePagColmn1">
                  <div class="dabblePageFormActions">
                    <span class=
                    "dabblePageFormButton dabblePageFormSubmit">
					<input name="save"
                    accesskey="s" id="dabblePageFormSubmit" value=
                    "Submit Form" type="submit" class=
                    "submit" /> 
					<?php echo button_to('Cancel',$referer, 'class=submit') ?>	
					<!-- <input name="cancel" value="Cancel"
                    type="submit" class="submit" /> -->
                                           &nbsp;&nbsp;Submitting this form make take several minutes to complete
					</span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="dabblePageBottomLeftShadow"></div>

    <div class="dabblePageBottomRightShadow"></div>

    <div class="dabblePageBottomShadow"></div>
  </div>
<div style="clear:both">&nbsp;</div>
<div style="clear:both">&nbsp;</div>
<div style="clear:both">&nbsp;</div>
<div style="clear:both">&nbsp;</div>
