#!/usr/bin/perl
# T. Beutel 12/23/2003
# Added Calgary U stuff 7/30/04

# Next step:
# - 7/7/06: add midweek series
#   - logic: if SR and date is M, Tu, We or Th, then make as SRMW
#   - for SRMW, instead of hotel, use: "New! Midweek series"


use Date::Manip;
use DBI;
use Data::Dumper;
use Sys::Hostname;
use strict;
use vars qw(%region_names);

print "Subject: cron: make_orsc_calendar\n";

# The result of this 
my $HTML;
my $INDEX;

# Midweek Days hash
my $days = { Tue=>1, Wed=>1, Thu=>1 };


# Database	    
my $dbh;
$dbh = DBI->connect("DBI:mysql:CTIDATABASE",'cticoaches','');

# Get all Fun, Ful, Bal, Pro, and ITB events

my $sql = <<EOT ;
SELECT id,fmid,event,course_type_id,region,location,date,start_date FROM event_calendar WHERE 
  course_type_id='18' OR
  course_type_id='21' OR
  course_type_id='22' OR
  course_type_id='23' OR
  course_type_id='53'
EOT

my $events = $dbh->selectall_arrayref($sql, { Columns => {} });

# Special exception for Calgary U.

foreach my $event (@$events){
  if($event->{region} eq 'RC'){
    $event->{region} = $event->{location};
    $event->{region} =~ s/ \- .* //xms;
  }
  $event->{region} = 'CLG'  if($event->{location} eq 'Calgary U');
  $event->{region} = 'LUWO' if($event->{location} eq 'UnivWOnt');
  $event->{region} = 'UCD'  if($event->{location} eq 'UC Davis');
  $event->{region} = 'NE'   if($event->{location} =~ m/ \A PROV /xms);

  if($event->{region} eq 'SR'){
    my $day = UnixDate($event->{start_date},'%a'); #'
    if($days->{$day}){
      $event->{region} = 'SRMW';
    }
  }
}

# Get all the regions being used in events

my %all_regions;
map { $all_regions{$_->{region}}++ } @$events;

# Get the region names by country

foreach my $country ('United States','Canada') {
print "Country: $country\n";

  $INDEX .=<<EOT ;
    <tr><td>&nbsp;</td></tr>
    <tr><td><h2>$country</h2></td></tr>
EOT


  my $names = $dbh->selectall_arrayref('SELECT region_code,region_name from regions where country=?',{ Columns => {} },$country);
  %region_names = map { $_->{region_code},$_->{region_name} } @$names;
  $region_names{SRMW} = $region_names{SR} if $country eq 'United States';

  print Dumper \%region_names;

  # Get only this country's regions from the events' regions

  my %regions = map { $_,1 } grep { exists $region_names{$_} } keys %all_regions;

  print 'Regions: ',Dumper \%regions;

  # Do each region in sort order
  foreach my $region (sort by_name keys %regions) {

    print "Region: $region\n";

    # Get only this region's events using grep
    my @region_events =
      grep { $_->{region} eq $region } @$events;

    # skip region if unless it has events
    next unless @region_events;

    # Initial counts
    my $total_events  = scalar @region_events;
    my $placed_events = 0;

    print "Total events: $total_events\n";

    # $placed_events is the number of events 'placed' into the calendar. Once $placed_events == $total_events,
    # the calendar is complete for this region

    # map dates to delta days from jan 1, 2000
    foreach my $event (@region_events) {
      my $err;
      my $values = DateCalc(ParseDate('1/1/2000'),ParseDate($event->{date}),\$err);
      my ($weeks,$days) = $values =~ m/0:0:(\d+):(\d+)/;
      $event->{delta} = $weeks*7+$days;
      #print "$event->{date} $event->{course_type_id} $event->{delta}\n";
    }


    my @region_events_sorted = sort { $a->{delta} <=> $b->{delta} } @region_events;

    #  print Dumper @region_events_sorted if $region eq 'DC';


    my @region_series;
    while ($placed_events < $total_events) {

      # start a new series (i.e. a line in the calendar
      my $series = { };
      my $delta  = 9999;

      # fill the series starting from the right (i.e. In The Bones)
      foreach my $type (53,23,22,21,18) {
	my @events = grep { $_->{course_type_id} == $type and not $_->{placed} } @region_events_sorted;

	# Get the closest earlier event
	my ($closest_earlier_event) =
	  reverse
	    sort { $a->{delta} <=> $b->{delta} }
	      grep { $_->{delta} < $delta } @events;



	# if there was one, put the date in the series
	if ($closest_earlier_event) {
	  $series->{$type} = { date  => $closest_earlier_event->{date},
			       delta => $closest_earlier_event->{delta},
			       # mark the color red if the location says -HOLD or region says SRMW
			       color => ($closest_earlier_event->{location} =~ m/-HOLD$/
                                         #or $closest_earlier_event->{region} eq 'SRMW'
                                        ) ? 'red' : 'black',

			     };
	  $delta = $closest_earlier_event->{delta};
	  $closest_earlier_event->{placed}++;
	  $placed_events++;
	}
      }

      push(@region_series,$series);

    }

    #print Dumper \@region_series  if($region eq 'SR');
    # create some HTML



	# Now store the calendar for this city code.

# Add region header...
    if($region =~ m/MW$/){  # ... midweek series

$HTML .=<<EOT ;
<!-- Midweek Series -->
<p><span style="color:#f00"><br><b>New!</b> Midweek series</span>.</p>
EOT
}

    else {

$INDEX .=<<EOT ;
    <tr><td><a href="#$region">$region_names{$region}</a></td></tr>
EOT

$HTML .=<<EOT ;
<!------------------------------------------------------>
<p><a name="$region"></a></p>
<table width="430" border="0" class="normal">
<tr>
<td width="331">&nbsp;<br>
<span class="header1"><b>$region_names{$region}</b></span>
EOT
 

# Make an exception for certain sites like Calgary University and Univ Western Ontario

if($region eq 'CLG'){
  $HTML .= q{
<br><br>CTI Courses in Calgary are offered by the University of Calgary.  If you are interested in registering, please call the university directly at 403-220-2877 or <a href="http://conted.ucalgary.ca/business/professionaldesignations/">click here to enroll</a> through the University's website.   Pricing is in Canadian dollars and may vary from CTI prices.
};
#'
} 

elsif($region eq 'LUWO'){
  $HTML .= q{
<br><br>The following CTI Courses are offered by the University of Western Ontario.  If you are interested in registering, please call the university directly at  (519) 661-3658 or <a href="http://www.uwo.ca/cstudies/">click here to enroll</a> through the University's website.   Pricing is in Canadian dollars and may vary from CTI prices.
};
#'
}

elsif($region eq 'UCD'){
  $HTML .= q{
<br><br>
The following CTI Courses are offered by the University of CAlifornia, Davis.  If you are interested in registering, please call the university directly at 1-800-752-0881 or <a href="http://www.universityextension.ucdavis.edu/">click here to enroll</a> through the University's website.   Pricing may vary from CTI prices.
};
#'

}


$HTML .=<<EOT ;
 </td>
<td>
<center>
<a href="#top" class="text">TOP</a>
</center>
</td>
</tr>
</table>
EOT


}


$HTML .=<<EOT ;
<table cellspacing="1" cellpadding="0" width="447" border="1" class="normal">
<tr>
<td width="19%" valign="top" bgcolor="white">
<center>
<b>ORSC Fundamentals</b><br>
</center>
</td>
<td width="20%" valign="top" bgcolor="white">
<center>
<b>Relationship Intelligence</b><br>
</center>
</td>
<td width="20%" valign="top" bgcolor="white">
<center>
<b>System Geography</b><br>
</center>
</td>
<td width="20%" valign="top" bgcolor="white">
<center>
<b>Relationship Path</b><br>
</center>
</td>
<td width="20%" valign="top" bgcolor="white">
<center>
<b>System Coaching Integration</b><br>
</center>
  </td>
  </tr>
EOT

    foreach my $series (sort using_special_magic @region_series) {
      $HTML .= "<tr>\n";
      foreach my $cell (18,21,22,23,53) {
	$HTML .=<<EOT ;
<td valign="top" width="19%" align="center"><font color="$series->{$cell}{color}">$series->{$cell}{date}&nbsp;</font></td>
EOT
      }
      $HTML .= "</tr>\n";
    }
    $HTML .= "</table>\n\n\n";
  }
}

print "Saving HTML code in calendar_cache...\n";

# store the INDEX and HTML
my $sth = $dbh->prepare('UPDATE calendar_cache set idx=?, html=?, created=now() where id=5');
$sth->execute($INDEX,$HTML);

print "Done.\n";

exit;

# the using_special_magic subroutine sorts series by looking at all the dates in the series
sub using_special_magic {
  $a->{18}{delta} <=> $b->{18}{delta} ||
  $a->{21}{delta} <=> $b->{21}{delta} ||
  $a->{22}{delta} <=> $b->{22}{delta} ||
  $a->{23}{delta} <=> $b->{23}{delta} ||
  $a->{53}{delta} <=> $b->{53}{delta}
}


# by_name sorts by region name
sub by_name { $region_names{$a} cmp $region_names{$b} }
