#!/bin/sh

event_type_ids='3 4 5 6 7'

for i in $event_type_ids; do echo $i; curl "http://www.thecoaches.com/portal/index.php/main/updateEventsFromFM?ctid=$i&key=1qASw2" > /dev/null; sleep 10;  done


