#!/bin/sh

event_type_ids='3 4 5 6 7 89 114 115 101 102 103 104 105 106 107 108 153 161 162 163 164 165 187'

for i in $event_type_ids; do echo $i; curl "http://www.thecoaches.com/portal/index.php/main/updateEventsFromFM?ctid=$i&key=1qASw2" > /dev/null; sleep 10;  done


