<?php

require 'lib/model/om/BaseCoachtrainingPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'coachtraining' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Mar  7 23:14:52 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CoachtrainingPeer extends BaseCoachtrainingPeer {

} // CoachtrainingPeer
