<?php

require 'lib/model/om/BaseCoachtraining.php';


/**
 * Skeleton subclass for representing a row from the 'coachtraining' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Mar  7 23:14:52 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Coachtraining extends BaseCoachtraining {


  public function setUnderstoodAgreements( $v ){
    $this->setExtra1( $v );
  }

  public function getUnderstoodAgreements( ) {
    return $this->getExtra1();
  }


  public function setBioResume( $v ){
    $this->setExtra2( $v ); // filename
  }

  public function getBioResume( ){
    return $this->getExtra2();
  }


} // Coachtraining
