<?php

require 'lib/model/om/BaseFlexformSubmission.php';


/**
 * Skeleton subclass for representing a row from the 'flexform_submission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May 21 23:14:40 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FlexformSubmission extends BaseFlexformSubmission {

  public function getKey( ){
    return $this->getExtra1();
  }

  public function setKey( $v ){
    if($v !== $this->getExtra1()){
      $this->setExtra1( $v );
    }
  }

  public function getPhoto(){
    // find upload question with keyword 'photo' in the label
    $c = new Criteria();
    $c->add( FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
    $c->add( FlexformAnswerPeer::TYPE, 'upload' ); 
    $c->add( FlexformAnswerPeer::LABEL, '%photo%' ,Criteria::LIKE );
    $flexform_answer = FlexformAnswerPeer::doSelectOne( $c );

    if(isset($flexform_answer)){
      return $flexform_answer->getContent();
    }
    return '';
  }

  public function getBioResume(){
    // find upload question with keyword 'photo' in the label
    $c = new Criteria();
    $c->add( FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
    $c->add( FlexformAnswerPeer::TYPE, 'upload' ); 
    $c->add( FlexformAnswerPeer::LABEL, '%resume%' ,Criteria::LIKE );
    $flexform_answer = FlexformAnswerPeer::doSelectOne( $c );

    commonTools::logMessage( 'FlexformSubmission->getBioResume()' );
    
    if(isset($flexform_answer)){
      
      $filename = $flexform_answer->getContent();

      return $filename;
    }
    return '';
  }

  public function getAnswerArray( ){
    $array = array( );

    $c = new Criteria();
    $c->add( FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
    $c->addAscendingOrderByColumn( FlexformAnswerPeer::DISPLAY_ORDER );
    $answers = FlexformAnswerPeer::doSelect( $c );

    return $answers;
  }


  public function exportAnswerArray( $mode = '' ){
    $array = array( );

    $c = new Criteria();
    $c->add( FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
    $answers = FlexformAnswerPeer::doSelect( $c );

    $fields = array( ); // to keep track of labels

    foreach($answers as $answer){
      if($mode == 'labels'){
        $field = $answer->getLabel();
        if(array_key_exists($field,$fields) && $fields[$field] == 1){ // check if this label is already used
          $field = $answer->getParamName();
        }
      }
      else {
        $field = $answer->getParamName();
      }

      $fields[$field] = 1;
      $text = $answer->getContent();

      $text = preg_replace('/\"/','""',$text);              // escape double quote ( " --> "" )
      $text = preg_replace("/[\n\r]/",' ',$text);           // convert newlines to spaces
      //$text = preg_replace('/[^(\x20-\x7F)]*/','', $text);  // remove all non-ascii chars
      $text = iconv('UTF-8', 'ASCII//TRANSLIT', $text); 

      $field = iconv('UTF-8', 'ASCII//TRANSLIT', $field); 

      $array[$field] = $text;
    }
    return $array;
  }


  public function saveAnswers( $request ){
    $msg = '';

    $profile = $this->getProfile();
    $fullname = $profile->getName(); // replace non-alpha with underscores

    // get all params returned by this request 
    $params = $request->getParameterHolder()->getAll();


    if(isset($params['flexform'])){
      $flexform_array = $params['flexform'];
      
      foreach($flexform_array as $param => $value){
        $c = new Criteria();
        $c->add(FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
        $c->add(FlexformAnswerPeer::PARAM_NAME, $param );
        $flexform_answer = FlexformAnswerPeer::doSelectOne( $c );
        if( ! isset($flexform_answer) ){
          return 'Error: FlexformSubmission saveAnswers: '.$param.' does not exist. Please contact CTI at 1-800-691-6008 and report this error.';
        }


        //commonTools::logMessage( "$param $value" );

          // save the answer as content
        $flexform_answer->setContent( $value );
        $flexform_answer->save();


        // if param matches first name, last name or email, then save in profile too
        if(preg_match('/firstname/i',$param)){
          $profile->setFirstName( $value );
        }
        if(preg_match('/lastname/i',$param)){
          $profile->setLastName( $value );
        }
        if(preg_match('/email/i',$param) && ! preg_match('/email2/i',$param) ){
          //$profile->setEmail1( $value ); // disabled T. Beutel 6/21/13 - overwriting the email address is bad because the
          // the email address is used for authentication
        }
      }
      $profile->save();
      $this->setSubmitDate( Date('Y-m-d H:i:s') );
      $this->save();
    }
    else {
      $msg = 'Error: FlexformSubmission saveAnswers: flexform params not present. Please contact CTI at 1-800-691-6008 and report this error.';
    }

    $uploadedFiles = $request->getFiles( );

// Example of $uploadedFiles
// 2013-05-30 15:29:32 Array
// (
//     [flexform] => Array
//         (
//             [photo123] => Array
//                 (
//                     [error] => 0
//                     [name] => medium.png
//                     [type] => image/png
//                     [tmp_name] => /tmp/phpSb9Pbp
//                     [size] => 105633
//                 )
//         )
// )


    //$debug = print_r($uploadedFiles, true);
    //commonTools::logMessage( $debug );

    if(isset($uploadedFiles['flexform'])){
      $flexform_file_array = $uploadedFiles['flexform'];
      
      foreach($flexform_file_array as $param => $file){

        if(file_exists($file["tmp_name"])){

          $c = new Criteria();
          $c->add(FlexformAnswerPeer::FLEXFORM_SUBMISSION_ID, $this->getId() );
          $c->add(FlexformAnswerPeer::PARAM_NAME, $param );
          $flexform_answer = FlexformAnswerPeer::doSelectOne( $c );
          if( ! isset($flexform_answer) ){
            return 'Error: FlexformSubmission saveAnswers: '.$param.' does not exist. Please contact CTI at 1-800-691-6008 and report this error.';
          }
          
          $filename = $fullname.'-'.$file["name"];
          $filename = preg_replace('/[^A-Za-z0-9\.\_]/','-',$filename); // replace non-alphanumberic, non-period, non-underscore with dash
          $filename = preg_replace('/^[^A-Za-z0-9]+/','',$filename); // remove non-alphanumeric from beginning of name
          move_uploaded_file($file["tmp_name"], sfConfig::get('sf_upload_dir').'/'.$filename);
          
          $flexform_answer->setContent( $filename );
          $flexform_answer->save();
        }

      }
    }

    return $msg;
  }


} // FlexformSubmission
