<?php

require 'lib/model/om/BaseFlexformAnswerPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'flexform_answer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May 21 23:14:41 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FlexformAnswerPeer extends BaseFlexformAnswerPeer {

  public static function initializeAnswers( $flexform_submission ){
    $flexform = $flexform_submission->getFlexform();
    
    // get questions
    $questions = $flexform->getQuestionArray();

    foreach($questions as $question){
      $answer = new FlexformAnswer();
      $answer->setFlexformSubmissionId( $flexform_submission->getId() );
      $answer->setFlexformQuestionId( $question->getId() );

      // add to answer
      $answer->setType(         $question->getType() );
      $answer->setNumber(       $question->getNumber() );
      $answer->setLabel(        $question->getLabel() );
      $answer->setParamName(    $question->getParamName() );
      $answer->setOptions(      $question->getOptions() );
      $answer->setCssClass(     $question->getCssClass() );
      $answer->setDisplayOrder( $question->getDisplayOrder() );

      $answer->save();
    }

    return;
  }
} // FlexformAnswerPeer
