<?php

require 'lib/model/om/BaseAnnualQuestionnaire.php';


/**
 * Skeleton subclass for representing a row from the 'annual_questionnaire' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Nov 11 20:47:00 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AnnualQuestionnaire extends BaseAnnualQuestionnaire {

} // AnnualQuestionnaire
