<?php

require 'lib/model/om/BasePodParticipantPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'pod_participant' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul 20 17:57:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PodParticipantPeer extends BasePodParticipantPeer {

} // PodParticipantPeer
