# default values
all:
  smtp_server_ip: 127.0.0.1
  base_domain: ww2.thecoaches.com
  pager_recs_max: 10
  webcomp:
    postkey: fjgh15t
    baseurl: http://webcomp.modelsmith.com/fmi-test/webcomp2_newFM
    getlevel: getlevel.php
