<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/20 19:15:04

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=mentordb',
  'username' => 'mentoruser',
  'password' => '2wSDe3',
  'encoding' => 'utf8',
  'port' => 3306,
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
