<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/11/05 18:05:23

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=certmatchdb',
  'username' => 'certmatchuser',
  'password' => '2wSDe3',
  'encoding' => 'utf8',
  'port' => 3306,
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
