<?php


/**
 * This class adds structure of 'workshop' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Sep 11 14:33:28 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class WorkshopMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.WorkshopMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(WorkshopPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(WorkshopPeer::TABLE_NAME);
		$tMap->setPhpName('Workshop');
		$tMap->setClassname('Workshop');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('CLIENT_ID', 'ClientId', 'INTEGER', 'client', 'ID', false, null);

		$tMap->addForeignKey('CATEGORY_ID', 'CategoryId', 'INTEGER', 'category', 'ID', false, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', false, 200);

		$tMap->addColumn('WORKSHOP_DATE', 'WorkshopDate', 'DATE', false, null);

		$tMap->addColumn('WORKSHOP_TIME', 'WorkshopTime', 'TIME', false, null);

		$tMap->addColumn('LOCATION', 'Location', 'VARCHAR', false, 100);

		$tMap->addColumn('COST', 'Cost', 'DECIMAL', false, null);

		$tMap->addColumn('LAST_DAY_TO_REGISTER', 'LastDayToRegister', 'DATE', false, null);

		$tMap->addColumn('MAX_NBR_ATTENDEES', 'MaxNbrAttendees', 'INTEGER', false, null);

		$tMap->addColumn('NBR_CURRENT_ATTENDEES', 'NbrCurrentAttendees', 'INTEGER', false, null);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null);

		$tMap->addColumn('LOGISTICS', 'Logistics', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // WorkshopMapBuilder
