<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/05 19:29:14

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=surveys',
  'username' => 'surveyuser',
  'password' => '2wSDe3',
  'encoding' => 'utf8',
  'port' => 3306,
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
