<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/07/05 19:29:15
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'leader' => 
  array (
    'is_secure' => false,
  ),
  'autologin' => 
  array (
    'is_secure' => false,
  ),
);
