<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/28 23:04:29

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=launchpaddb',
  'username' => 'launchpaduser',
  'password' => '2wSDe3',
  'encoding' => 'utf8',
  'port' => 3306,
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
